accounts:
  - name: max
    coins: ["20000bet", "200000000000bty"]
  - name: fedor
    coins: ["10000bet", "20000000000bty"]
  - name: sim
    coins: ["10000bet", "100000000bty"]
validator:
  name: fedor
  staked: "100000000bty"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: max
  coins: ["5bet", "2000000000bty"]
