// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: publicevents/fihish_pub_event.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FihishPubEvent struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PubId   string `protobuf:"bytes,3,opt,name=pubId,proto3" json:"pubId,omitempty"`
}

func (m *FihishPubEvent) Reset()         { *m = FihishPubEvent{} }
func (m *FihishPubEvent) String() string { return proto.CompactTextString(m) }
func (*FihishPubEvent) ProtoMessage()    {}
func (*FihishPubEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfbb705825509ce0, []int{0}
}
func (m *FihishPubEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FihishPubEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FihishPubEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FihishPubEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FihishPubEvent.Merge(m, src)
}
func (m *FihishPubEvent) XXX_Size() int {
	return m.Size()
}
func (m *FihishPubEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_FihishPubEvent.DiscardUnknown(m)
}

var xxx_messageInfo_FihishPubEvent proto.InternalMessageInfo

func (m *FihishPubEvent) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *FihishPubEvent) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FihishPubEvent) GetPubId() string {
	if m != nil {
		return m.PubId
	}
	return ""
}

func init() {
	proto.RegisterType((*FihishPubEvent)(nil), "VoroshilovMax.bettery.publicevents.FihishPubEvent")
}

func init() {
	proto.RegisterFile("publicevents/fihish_pub_event.proto", fileDescriptor_cfbb705825509ce0)
}

var fileDescriptor_cfbb705825509ce0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x28, 0x4d, 0xca,
	0xc9, 0x4c, 0x4e, 0x2d, 0x4b, 0xcd, 0x2b, 0x29, 0xd6, 0x4f, 0xcb, 0xcc, 0xc8, 0x2c, 0xce, 0x88,
	0x2f, 0x28, 0x4d, 0x8a, 0x07, 0x8b, 0xe8, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x29, 0x85, 0xe5,
	0x17, 0xe5, 0x17, 0x67, 0x64, 0xe6, 0xe4, 0x97, 0xf9, 0x26, 0x56, 0xe8, 0x25, 0xa5, 0x96, 0x94,
	0xa4, 0x16, 0x55, 0xea, 0x21, 0x6b, 0x95, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x2b, 0xd7, 0x07,
	0xb1, 0x20, 0x3a, 0x95, 0x02, 0xb8, 0xf8, 0xdc, 0xc0, 0x66, 0x06, 0x94, 0x26, 0xb9, 0x82, 0x14,
	0x0a, 0x49, 0x70, 0xb1, 0x27, 0x17, 0xa5, 0x26, 0x96, 0xe4, 0x17, 0x49, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0xc1, 0xb8, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x2c,
	0x41, 0x4c, 0x99, 0x29, 0x42, 0x22, 0x5c, 0xac, 0x05, 0xa5, 0x49, 0x9e, 0x29, 0x12, 0xcc, 0x60,
	0x75, 0x10, 0x8e, 0x93, 0xff, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24,
	0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x99,
	0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa3, 0x38, 0x58, 0x1f, 0xea,
	0x60, 0xfd, 0x0a, 0x7d, 0x14, 0xdf, 0x96, 0x54, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0x5d, 0x6a,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x81, 0xa3, 0xfe, 0xf7, 0x0a, 0x01, 0x00, 0x00,
}

func (m *FihishPubEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FihishPubEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FihishPubEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PubId) > 0 {
		i -= len(m.PubId)
		copy(dAtA[i:], m.PubId)
		i = encodeVarintFihishPubEvent(dAtA, i, uint64(len(m.PubId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintFihishPubEvent(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintFihishPubEvent(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFihishPubEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovFihishPubEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FihishPubEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovFihishPubEvent(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovFihishPubEvent(uint64(m.Id))
	}
	l = len(m.PubId)
	if l > 0 {
		n += 1 + l + sovFihishPubEvent(uint64(l))
	}
	return n
}

func sovFihishPubEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFihishPubEvent(x uint64) (n int) {
	return sovFihishPubEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FihishPubEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFihishPubEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FihishPubEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FihishPubEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFihishPubEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFihishPubEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFihishPubEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFihishPubEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFihishPubEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFihishPubEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFihishPubEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFihishPubEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFihishPubEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFihishPubEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFihishPubEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFihishPubEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFihishPubEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFihishPubEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFihishPubEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFihishPubEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFihishPubEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFihishPubEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFihishPubEvent = fmt.Errorf("proto: unexpected end of group")
)
