// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: publicevents/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetCreatePubEventsRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetCreatePubEventsRequest) Reset()         { *m = QueryGetCreatePubEventsRequest{} }
func (m *QueryGetCreatePubEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCreatePubEventsRequest) ProtoMessage()    {}
func (*QueryGetCreatePubEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{0}
}
func (m *QueryGetCreatePubEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCreatePubEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCreatePubEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCreatePubEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCreatePubEventsRequest.Merge(m, src)
}
func (m *QueryGetCreatePubEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCreatePubEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCreatePubEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCreatePubEventsRequest proto.InternalMessageInfo

func (m *QueryGetCreatePubEventsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetCreatePubEventsResponse struct {
	CreatePubEvents *CreatePubEvents `protobuf:"bytes,1,opt,name=CreatePubEvents,proto3" json:"CreatePubEvents,omitempty"`
}

func (m *QueryGetCreatePubEventsResponse) Reset()         { *m = QueryGetCreatePubEventsResponse{} }
func (m *QueryGetCreatePubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCreatePubEventsResponse) ProtoMessage()    {}
func (*QueryGetCreatePubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{1}
}
func (m *QueryGetCreatePubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCreatePubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCreatePubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCreatePubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCreatePubEventsResponse.Merge(m, src)
}
func (m *QueryGetCreatePubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCreatePubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCreatePubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCreatePubEventsResponse proto.InternalMessageInfo

func (m *QueryGetCreatePubEventsResponse) GetCreatePubEvents() *CreatePubEvents {
	if m != nil {
		return m.CreatePubEvents
	}
	return nil
}

type QueryAllCreatePubEventsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCreatePubEventsRequest) Reset()         { *m = QueryAllCreatePubEventsRequest{} }
func (m *QueryAllCreatePubEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCreatePubEventsRequest) ProtoMessage()    {}
func (*QueryAllCreatePubEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{2}
}
func (m *QueryAllCreatePubEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCreatePubEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCreatePubEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCreatePubEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCreatePubEventsRequest.Merge(m, src)
}
func (m *QueryAllCreatePubEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCreatePubEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCreatePubEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCreatePubEventsRequest proto.InternalMessageInfo

func (m *QueryAllCreatePubEventsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCreatePubEventsResponse struct {
	CreatePubEvents []*CreatePubEvents  `protobuf:"bytes,1,rep,name=CreatePubEvents,proto3" json:"CreatePubEvents,omitempty"`
	Pagination      *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCreatePubEventsResponse) Reset()         { *m = QueryAllCreatePubEventsResponse{} }
func (m *QueryAllCreatePubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCreatePubEventsResponse) ProtoMessage()    {}
func (*QueryAllCreatePubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{3}
}
func (m *QueryAllCreatePubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCreatePubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCreatePubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCreatePubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCreatePubEventsResponse.Merge(m, src)
}
func (m *QueryAllCreatePubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCreatePubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCreatePubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCreatePubEventsResponse proto.InternalMessageInfo

func (m *QueryAllCreatePubEventsResponse) GetCreatePubEvents() []*CreatePubEvents {
	if m != nil {
		return m.CreatePubEvents
	}
	return nil
}

func (m *QueryAllCreatePubEventsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetCreatePubEventsRequest)(nil), "VoroshilovMax.bettery.publicevents.QueryGetCreatePubEventsRequest")
	proto.RegisterType((*QueryGetCreatePubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.QueryGetCreatePubEventsResponse")
	proto.RegisterType((*QueryAllCreatePubEventsRequest)(nil), "VoroshilovMax.bettery.publicevents.QueryAllCreatePubEventsRequest")
	proto.RegisterType((*QueryAllCreatePubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.QueryAllCreatePubEventsResponse")
}

func init() { proto.RegisterFile("publicevents/query.proto", fileDescriptor_668bd8c5c29a02c6) }

var fileDescriptor_668bd8c5c29a02c6 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x41, 0xeb, 0x12, 0x41,
	0x18, 0xc6, 0x9d, 0xb5, 0x3a, 0x4c, 0x50, 0x30, 0x27, 0x91, 0xd8, 0x62, 0x89, 0x8a, 0x0e, 0x33,
	0xa9, 0x08, 0x51, 0x97, 0x54, 0xca, 0x53, 0x64, 0x1e, 0x3a, 0x04, 0x21, 0x33, 0xeb, 0xb0, 0x0e,
	0xac, 0x3b, 0xeb, 0xce, 0xac, 0x28, 0x11, 0x44, 0x9f, 0x20, 0xe8, 0x23, 0x75, 0xa9, 0x9b, 0xd0,
	0x25, 0xa2, 0x43, 0x68, 0x1f, 0x24, 0x9c, 0xd9, 0xca, 0xdd, 0x5c, 0xcd, 0xfa, 0x5f, 0x9d, 0x67,
	0x7e, 0xf3, 0xfc, 0x5e, 0x5f, 0x16, 0xd6, 0xe2, 0x94, 0x85, 0xc2, 0xe7, 0x73, 0x1e, 0x69, 0x45,
	0x66, 0x29, 0x4f, 0x96, 0x38, 0x4e, 0xa4, 0x96, 0xc8, 0x7b, 0x26, 0x13, 0xa9, 0x26, 0x22, 0x94,
	0xf3, 0xc7, 0x74, 0x81, 0x19, 0xd7, 0xda, 0x1c, 0xee, 0xe4, 0xeb, 0x57, 0x02, 0x29, 0x83, 0x90,
	0x13, 0x1a, 0x0b, 0x42, 0xa3, 0x48, 0x6a, 0xaa, 0x85, 0x8c, 0x94, 0x25, 0xd4, 0x6f, 0xfb, 0x52,
	0x4d, 0xa5, 0x22, 0x8c, 0x2a, 0x6e, 0xd1, 0x64, 0xde, 0x60, 0x5c, 0xd3, 0x06, 0x89, 0x69, 0x20,
	0x22, 0x13, 0xce, 0xb2, 0xd7, 0x73, 0x3d, 0xfc, 0x84, 0x53, 0xcd, 0x47, 0x71, 0xca, 0x46, 0xf6,
	0x17, 0x9b, 0xf2, 0xee, 0x40, 0xf7, 0xe9, 0x96, 0xd3, 0xe7, 0xba, 0x67, 0x22, 0x83, 0x94, 0x3d,
	0x34, 0x81, 0x21, 0x9f, 0xa5, 0x5c, 0x69, 0x74, 0x09, 0x3a, 0x62, 0x5c, 0x03, 0xd7, 0xc0, 0xad,
	0x73, 0x43, 0x47, 0x8c, 0xbd, 0xd7, 0x00, 0x5e, 0x2d, 0xbd, 0xa2, 0x62, 0x19, 0x29, 0x8e, 0x5e,
	0xc0, 0xcb, 0x85, 0x23, 0x03, 0xb8, 0xd8, 0x6c, 0xe1, 0xe3, 0x33, 0xc0, 0x45, 0x6a, 0x91, 0xe5,
	0x4d, 0xb2, 0xd2, 0x9d, 0x30, 0x2c, 0x29, 0xfd, 0x08, 0xc2, 0xdf, 0x03, 0xc9, 0xde, 0xbe, 0x81,
	0xed, 0xf4, 0xf0, 0x76, 0x7a, 0xd8, 0xfe, 0x31, 0xd9, 0xf4, 0xf0, 0x80, 0x06, 0x3c, 0xbb, 0x3b,
	0xdc, 0xb9, 0xe9, 0x7d, 0xfc, 0x29, 0xbb, 0xef, 0xa9, 0x43, 0xb2, 0xd5, 0xb3, 0x92, 0x45, 0xfd,
	0x9c, 0x8a, 0x63, 0x54, 0x6e, 0x1e, 0x55, 0xb1, 0xdd, 0x76, 0x5d, 0x9a, 0xef, 0xab, 0xf0, 0xbc,
	0x71, 0x41, 0x5f, 0xc1, 0x1f, 0x95, 0x51, 0xf7, 0x6f, 0xca, 0x1e, 0x5e, 0x95, 0x7a, 0xef, 0xbf,
	0x18, 0xb6, 0xb2, 0xf7, 0xe0, 0xcd, 0xa7, 0xef, 0xef, 0x9c, 0x7b, 0xe8, 0x2e, 0xc9, 0xc1, 0x48,
	0x06, 0x23, 0x7b, 0xd6, 0xfa, 0x17, 0x84, 0xbc, 0x14, 0xe3, 0x57, 0xe8, 0x0b, 0x80, 0xa8, 0x40,
	0xef, 0x84, 0xe1, 0x09, 0x86, 0xa5, 0x7b, 0x75, 0x82, 0x61, 0xf9, 0xc2, 0x78, 0xf7, 0x8d, 0x61,
	0x1b, 0xb5, 0xfe, 0xc1, 0xb0, 0xfb, 0xe4, 0xc3, 0xda, 0x05, 0xab, 0xb5, 0x0b, 0xbe, 0xad, 0x5d,
	0xf0, 0x76, 0xe3, 0x56, 0x56, 0x1b, 0xb7, 0xf2, 0x79, 0xe3, 0x56, 0x9e, 0xb7, 0x03, 0xa1, 0x27,
	0x29, 0xc3, 0xbe, 0x9c, 0x96, 0x80, 0x17, 0x79, 0xb4, 0x5e, 0xc6, 0x5c, 0xb1, 0x0b, 0xe6, 0x43,
	0xd0, 0xfa, 0x11, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xf5, 0x84, 0x80, 0xb8, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a createPubEvents by id.
	CreatePubEvents(ctx context.Context, in *QueryGetCreatePubEventsRequest, opts ...grpc.CallOption) (*QueryGetCreatePubEventsResponse, error)
	// Queries a list of createPubEvents items.
	CreatePubEventsAll(ctx context.Context, in *QueryAllCreatePubEventsRequest, opts ...grpc.CallOption) (*QueryAllCreatePubEventsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CreatePubEvents(ctx context.Context, in *QueryGetCreatePubEventsRequest, opts ...grpc.CallOption) (*QueryGetCreatePubEventsResponse, error) {
	out := new(QueryGetCreatePubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Query/CreatePubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CreatePubEventsAll(ctx context.Context, in *QueryAllCreatePubEventsRequest, opts ...grpc.CallOption) (*QueryAllCreatePubEventsResponse, error) {
	out := new(QueryAllCreatePubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Query/CreatePubEventsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a createPubEvents by id.
	CreatePubEvents(context.Context, *QueryGetCreatePubEventsRequest) (*QueryGetCreatePubEventsResponse, error)
	// Queries a list of createPubEvents items.
	CreatePubEventsAll(context.Context, *QueryAllCreatePubEventsRequest) (*QueryAllCreatePubEventsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) CreatePubEvents(ctx context.Context, req *QueryGetCreatePubEventsRequest) (*QueryGetCreatePubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePubEvents not implemented")
}
func (*UnimplementedQueryServer) CreatePubEventsAll(ctx context.Context, req *QueryAllCreatePubEventsRequest) (*QueryAllCreatePubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePubEventsAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_CreatePubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCreatePubEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CreatePubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Query/CreatePubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CreatePubEvents(ctx, req.(*QueryGetCreatePubEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CreatePubEventsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCreatePubEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CreatePubEventsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Query/CreatePubEventsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CreatePubEventsAll(ctx, req.(*QueryAllCreatePubEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VoroshilovMax.bettery.publicevents.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePubEvents",
			Handler:    _Query_CreatePubEvents_Handler,
		},
		{
			MethodName: "CreatePubEventsAll",
			Handler:    _Query_CreatePubEventsAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publicevents/query.proto",
}

func (m *QueryGetCreatePubEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCreatePubEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCreatePubEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCreatePubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCreatePubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCreatePubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatePubEvents != nil {
		{
			size, err := m.CreatePubEvents.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCreatePubEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCreatePubEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCreatePubEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCreatePubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCreatePubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCreatePubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.CreatePubEvents) > 0 {
		for iNdEx := len(m.CreatePubEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CreatePubEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetCreatePubEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetCreatePubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CreatePubEvents != nil {
		l = m.CreatePubEvents.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCreatePubEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCreatePubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CreatePubEvents) > 0 {
		for _, e := range m.CreatePubEvents {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetCreatePubEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCreatePubEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCreatePubEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCreatePubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCreatePubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCreatePubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatePubEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatePubEvents == nil {
				m.CreatePubEvents = &CreatePubEvents{}
			}
			if err := m.CreatePubEvents.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCreatePubEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCreatePubEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCreatePubEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCreatePubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCreatePubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCreatePubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatePubEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatePubEvents = append(m.CreatePubEvents, &CreatePubEvents{})
			if err := m.CreatePubEvents[len(m.CreatePubEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
