// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: publicevents/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetValidPubEventsRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetValidPubEventsRequest) Reset()         { *m = QueryGetValidPubEventsRequest{} }
func (m *QueryGetValidPubEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetValidPubEventsRequest) ProtoMessage()    {}
func (*QueryGetValidPubEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{0}
}
func (m *QueryGetValidPubEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetValidPubEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetValidPubEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetValidPubEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetValidPubEventsRequest.Merge(m, src)
}
func (m *QueryGetValidPubEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetValidPubEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetValidPubEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetValidPubEventsRequest proto.InternalMessageInfo

func (m *QueryGetValidPubEventsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetValidPubEventsResponse struct {
	ValidPubEvents *ValidPubEvents `protobuf:"bytes,1,opt,name=ValidPubEvents,proto3" json:"ValidPubEvents,omitempty"`
}

func (m *QueryGetValidPubEventsResponse) Reset()         { *m = QueryGetValidPubEventsResponse{} }
func (m *QueryGetValidPubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetValidPubEventsResponse) ProtoMessage()    {}
func (*QueryGetValidPubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{1}
}
func (m *QueryGetValidPubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetValidPubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetValidPubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetValidPubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetValidPubEventsResponse.Merge(m, src)
}
func (m *QueryGetValidPubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetValidPubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetValidPubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetValidPubEventsResponse proto.InternalMessageInfo

func (m *QueryGetValidPubEventsResponse) GetValidPubEvents() *ValidPubEvents {
	if m != nil {
		return m.ValidPubEvents
	}
	return nil
}

type QueryAllValidPubEventsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllValidPubEventsRequest) Reset()         { *m = QueryAllValidPubEventsRequest{} }
func (m *QueryAllValidPubEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllValidPubEventsRequest) ProtoMessage()    {}
func (*QueryAllValidPubEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{2}
}
func (m *QueryAllValidPubEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllValidPubEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllValidPubEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllValidPubEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllValidPubEventsRequest.Merge(m, src)
}
func (m *QueryAllValidPubEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllValidPubEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllValidPubEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllValidPubEventsRequest proto.InternalMessageInfo

func (m *QueryAllValidPubEventsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllValidPubEventsResponse struct {
	ValidPubEvents []*ValidPubEvents   `protobuf:"bytes,1,rep,name=ValidPubEvents,proto3" json:"ValidPubEvents,omitempty"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllValidPubEventsResponse) Reset()         { *m = QueryAllValidPubEventsResponse{} }
func (m *QueryAllValidPubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllValidPubEventsResponse) ProtoMessage()    {}
func (*QueryAllValidPubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{3}
}
func (m *QueryAllValidPubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllValidPubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllValidPubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllValidPubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllValidPubEventsResponse.Merge(m, src)
}
func (m *QueryAllValidPubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllValidPubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllValidPubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllValidPubEventsResponse proto.InternalMessageInfo

func (m *QueryAllValidPubEventsResponse) GetValidPubEvents() []*ValidPubEvents {
	if m != nil {
		return m.ValidPubEvents
	}
	return nil
}

func (m *QueryAllValidPubEventsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetPartPubEventsRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetPartPubEventsRequest) Reset()         { *m = QueryGetPartPubEventsRequest{} }
func (m *QueryGetPartPubEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPartPubEventsRequest) ProtoMessage()    {}
func (*QueryGetPartPubEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{4}
}
func (m *QueryGetPartPubEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPartPubEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPartPubEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPartPubEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPartPubEventsRequest.Merge(m, src)
}
func (m *QueryGetPartPubEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPartPubEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPartPubEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPartPubEventsRequest proto.InternalMessageInfo

func (m *QueryGetPartPubEventsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetPartPubEventsResponse struct {
	PartPubEvents *PartPubEvents `protobuf:"bytes,1,opt,name=PartPubEvents,proto3" json:"PartPubEvents,omitempty"`
}

func (m *QueryGetPartPubEventsResponse) Reset()         { *m = QueryGetPartPubEventsResponse{} }
func (m *QueryGetPartPubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPartPubEventsResponse) ProtoMessage()    {}
func (*QueryGetPartPubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{5}
}
func (m *QueryGetPartPubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPartPubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPartPubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPartPubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPartPubEventsResponse.Merge(m, src)
}
func (m *QueryGetPartPubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPartPubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPartPubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPartPubEventsResponse proto.InternalMessageInfo

func (m *QueryGetPartPubEventsResponse) GetPartPubEvents() *PartPubEvents {
	if m != nil {
		return m.PartPubEvents
	}
	return nil
}

type QueryAllPartPubEventsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPartPubEventsRequest) Reset()         { *m = QueryAllPartPubEventsRequest{} }
func (m *QueryAllPartPubEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPartPubEventsRequest) ProtoMessage()    {}
func (*QueryAllPartPubEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{6}
}
func (m *QueryAllPartPubEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPartPubEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPartPubEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPartPubEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPartPubEventsRequest.Merge(m, src)
}
func (m *QueryAllPartPubEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPartPubEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPartPubEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPartPubEventsRequest proto.InternalMessageInfo

func (m *QueryAllPartPubEventsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPartPubEventsResponse struct {
	PartPubEvents []*PartPubEvents    `protobuf:"bytes,1,rep,name=PartPubEvents,proto3" json:"PartPubEvents,omitempty"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPartPubEventsResponse) Reset()         { *m = QueryAllPartPubEventsResponse{} }
func (m *QueryAllPartPubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPartPubEventsResponse) ProtoMessage()    {}
func (*QueryAllPartPubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{7}
}
func (m *QueryAllPartPubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPartPubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPartPubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPartPubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPartPubEventsResponse.Merge(m, src)
}
func (m *QueryAllPartPubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPartPubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPartPubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPartPubEventsResponse proto.InternalMessageInfo

func (m *QueryAllPartPubEventsResponse) GetPartPubEvents() []*PartPubEvents {
	if m != nil {
		return m.PartPubEvents
	}
	return nil
}

func (m *QueryAllPartPubEventsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetCreatePubEventsRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetCreatePubEventsRequest) Reset()         { *m = QueryGetCreatePubEventsRequest{} }
func (m *QueryGetCreatePubEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCreatePubEventsRequest) ProtoMessage()    {}
func (*QueryGetCreatePubEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{8}
}
func (m *QueryGetCreatePubEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCreatePubEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCreatePubEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCreatePubEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCreatePubEventsRequest.Merge(m, src)
}
func (m *QueryGetCreatePubEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCreatePubEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCreatePubEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCreatePubEventsRequest proto.InternalMessageInfo

func (m *QueryGetCreatePubEventsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetCreatePubEventsResponse struct {
	CreatePubEvents *CreatePubEvents `protobuf:"bytes,1,opt,name=CreatePubEvents,proto3" json:"CreatePubEvents,omitempty"`
}

func (m *QueryGetCreatePubEventsResponse) Reset()         { *m = QueryGetCreatePubEventsResponse{} }
func (m *QueryGetCreatePubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCreatePubEventsResponse) ProtoMessage()    {}
func (*QueryGetCreatePubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{9}
}
func (m *QueryGetCreatePubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCreatePubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCreatePubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCreatePubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCreatePubEventsResponse.Merge(m, src)
}
func (m *QueryGetCreatePubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCreatePubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCreatePubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCreatePubEventsResponse proto.InternalMessageInfo

func (m *QueryGetCreatePubEventsResponse) GetCreatePubEvents() *CreatePubEvents {
	if m != nil {
		return m.CreatePubEvents
	}
	return nil
}

type QueryAllCreatePubEventsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCreatePubEventsRequest) Reset()         { *m = QueryAllCreatePubEventsRequest{} }
func (m *QueryAllCreatePubEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCreatePubEventsRequest) ProtoMessage()    {}
func (*QueryAllCreatePubEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{10}
}
func (m *QueryAllCreatePubEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCreatePubEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCreatePubEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCreatePubEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCreatePubEventsRequest.Merge(m, src)
}
func (m *QueryAllCreatePubEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCreatePubEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCreatePubEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCreatePubEventsRequest proto.InternalMessageInfo

func (m *QueryAllCreatePubEventsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCreatePubEventsResponse struct {
	CreatePubEvents []*CreatePubEvents  `protobuf:"bytes,1,rep,name=CreatePubEvents,proto3" json:"CreatePubEvents,omitempty"`
	Pagination      *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCreatePubEventsResponse) Reset()         { *m = QueryAllCreatePubEventsResponse{} }
func (m *QueryAllCreatePubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCreatePubEventsResponse) ProtoMessage()    {}
func (*QueryAllCreatePubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_668bd8c5c29a02c6, []int{11}
}
func (m *QueryAllCreatePubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCreatePubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCreatePubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCreatePubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCreatePubEventsResponse.Merge(m, src)
}
func (m *QueryAllCreatePubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCreatePubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCreatePubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCreatePubEventsResponse proto.InternalMessageInfo

func (m *QueryAllCreatePubEventsResponse) GetCreatePubEvents() []*CreatePubEvents {
	if m != nil {
		return m.CreatePubEvents
	}
	return nil
}

func (m *QueryAllCreatePubEventsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetValidPubEventsRequest)(nil), "VoroshilovMax.bettery.publicevents.QueryGetValidPubEventsRequest")
	proto.RegisterType((*QueryGetValidPubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.QueryGetValidPubEventsResponse")
	proto.RegisterType((*QueryAllValidPubEventsRequest)(nil), "VoroshilovMax.bettery.publicevents.QueryAllValidPubEventsRequest")
	proto.RegisterType((*QueryAllValidPubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.QueryAllValidPubEventsResponse")
	proto.RegisterType((*QueryGetPartPubEventsRequest)(nil), "VoroshilovMax.bettery.publicevents.QueryGetPartPubEventsRequest")
	proto.RegisterType((*QueryGetPartPubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.QueryGetPartPubEventsResponse")
	proto.RegisterType((*QueryAllPartPubEventsRequest)(nil), "VoroshilovMax.bettery.publicevents.QueryAllPartPubEventsRequest")
	proto.RegisterType((*QueryAllPartPubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.QueryAllPartPubEventsResponse")
	proto.RegisterType((*QueryGetCreatePubEventsRequest)(nil), "VoroshilovMax.bettery.publicevents.QueryGetCreatePubEventsRequest")
	proto.RegisterType((*QueryGetCreatePubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.QueryGetCreatePubEventsResponse")
	proto.RegisterType((*QueryAllCreatePubEventsRequest)(nil), "VoroshilovMax.bettery.publicevents.QueryAllCreatePubEventsRequest")
	proto.RegisterType((*QueryAllCreatePubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.QueryAllCreatePubEventsResponse")
}

func init() { proto.RegisterFile("publicevents/query.proto", fileDescriptor_668bd8c5c29a02c6) }

var fileDescriptor_668bd8c5c29a02c6 = []byte{
	// 676 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x41, 0x6f, 0xd3, 0x3e,
	0x18, 0xc6, 0xe7, 0xee, 0xff, 0xe7, 0x60, 0xc4, 0x00, 0x9f, 0xa6, 0x6a, 0x04, 0x64, 0x10, 0x20,
	0x0e, 0x09, 0x6d, 0x19, 0x6c, 0x43, 0x82, 0x75, 0x13, 0xec, 0x84, 0x18, 0x3d, 0x0c, 0x69, 0x12,
	0x9a, 0x9c, 0xd6, 0xa4, 0x91, 0xb2, 0x38, 0x4b, 0x9c, 0xaa, 0x13, 0x20, 0x21, 0x3e, 0x01, 0x12,
	0x1f, 0x81, 0x4f, 0xc2, 0x01, 0x09, 0x6e, 0x13, 0x20, 0x34, 0x21, 0x0e, 0xa8, 0xe5, 0x83, 0xa0,
	0x3a, 0x1e, 0xad, 0xd3, 0xa4, 0x4d, 0x68, 0xae, 0xf5, 0xeb, 0xc7, 0xcf, 0xef, 0x7d, 0xe2, 0xd7,
	0x85, 0x8b, 0x5e, 0x68, 0x3a, 0x76, 0x93, 0x76, 0xa8, 0xcb, 0x03, 0xe3, 0x20, 0xa4, 0xfe, 0xa1,
	0xee, 0xf9, 0x8c, 0x33, 0x84, 0x77, 0x98, 0xcf, 0x82, 0xb6, 0xed, 0xb0, 0xce, 0x23, 0xd2, 0xd5,
	0x4d, 0xca, 0xb9, 0x58, 0x1c, 0xa9, 0x2f, 0x2f, 0x59, 0x8c, 0x59, 0x0e, 0x35, 0x88, 0x67, 0x1b,
	0xc4, 0x75, 0x19, 0x27, 0xdc, 0x66, 0x6e, 0x10, 0x29, 0x94, 0x6f, 0x34, 0x59, 0xb0, 0xcf, 0x02,
	0xc3, 0x24, 0x01, 0x8d, 0xa4, 0x8d, 0x4e, 0xc5, 0xa4, 0x9c, 0x54, 0x0c, 0x8f, 0x58, 0xb6, 0x2b,
	0x8a, 0x65, 0xed, 0x65, 0xc5, 0x47, 0x87, 0x38, 0x76, 0x6b, 0xcf, 0x0b, 0xcd, 0xbd, 0xe8, 0x07,
	0x59, 0x84, 0x95, 0x22, 0x8f, 0xf8, 0x7c, 0xbc, 0xe6, 0x8a, 0x52, 0xd3, 0xf4, 0x29, 0xe1, 0x74,
	0xac, 0x0a, 0x1b, 0xf0, 0xc2, 0x93, 0x81, 0xa1, 0x2d, 0xca, 0x77, 0x06, 0x67, 0x6d, 0x87, 0xe6,
	0x03, 0xb1, 0xde, 0xa0, 0x07, 0x21, 0x0d, 0x38, 0x5a, 0x80, 0x25, 0xbb, 0xb5, 0x08, 0x2e, 0x81,
	0xeb, 0xff, 0x35, 0x4a, 0x76, 0x0b, 0xbf, 0x84, 0x5a, 0xda, 0x86, 0xc0, 0x63, 0x6e, 0x40, 0xd1,
	0x2e, 0x5c, 0x50, 0x57, 0xc4, 0xee, 0xd3, 0xd5, 0xaa, 0x3e, 0xbd, 0x91, 0x7a, 0x4c, 0x33, 0xa6,
	0x84, 0x2d, 0x69, 0xb7, 0xee, 0x38, 0xc9, 0x76, 0x1f, 0x42, 0x38, 0x6c, 0xa9, 0x3c, 0xf8, 0xaa,
	0x1e, 0xf5, 0x5f, 0x1f, 0xf4, 0x5f, 0x8f, 0xa2, 0x95, 0xfd, 0xd7, 0xb7, 0x89, 0x45, 0xe5, 0xde,
	0xc6, 0xc8, 0x4e, 0xfc, 0x11, 0x48, 0xce, 0x84, 0x93, 0x26, 0x70, 0xce, 0x17, 0xc3, 0x89, 0xb6,
	0x14, 0x8c, 0x92, 0xc0, 0xb8, 0x36, 0x15, 0x23, 0x32, 0xa6, 0x70, 0xe8, 0x70, 0xe9, 0x24, 0xae,
	0x6d, 0xe2, 0xf3, 0xa9, 0xf1, 0x76, 0x87, 0xdf, 0x43, 0xac, 0x5e, 0x52, 0x3f, 0x85, 0x67, 0x94,
	0x05, 0xd9, 0xe3, 0x4a, 0x16, 0x68, 0x55, 0x51, 0xd5, 0xc1, 0xcf, 0xa5, 0xd3, 0xba, 0xe3, 0x24,
	0x3a, 0x2d, 0x2a, 0xd9, 0x0f, 0x60, 0xf8, 0x0d, 0x65, 0x46, 0x9c, 0x2f, 0x02, 0xb1, 0xb8, 0x54,
	0x6f, 0x0e, 0x2f, 0xe1, 0xa6, 0xb8, 0xd8, 0x53, 0x73, 0x7d, 0x0d, 0xe0, 0xc5, 0xd4, 0x2d, 0x92,
	0xfb, 0x19, 0x3c, 0x1b, 0x5b, 0x92, 0x6d, 0xae, 0x65, 0x21, 0x8f, 0xab, 0xc6, 0xb5, 0x70, 0x7b,
	0x78, 0xa3, 0x52, 0x4c, 0x17, 0x15, 0xf1, 0xe7, 0x13, 0xd8, 0xa4, 0xa3, 0x26, 0xc1, 0xce, 0x17,
	0x05, 0x5b, 0x58, 0xd4, 0xd5, 0xf7, 0x10, 0xfe, 0x2f, 0x58, 0xd0, 0x31, 0x88, 0x0f, 0x1c, 0x54,
	0xcf, 0xe2, 0x75, 0xe2, 0x7c, 0x2f, 0x6f, 0xcc, 0x22, 0x11, 0xf9, 0xc5, 0xf7, 0xdf, 0x7c, 0xfd,
	0xfd, 0xae, 0xb4, 0x8a, 0xee, 0x18, 0x8a, 0x96, 0x21, 0xb5, 0x8c, 0xf1, 0x27, 0xed, 0xaf, 0x86,
	0xf1, 0xc2, 0x6e, 0xbd, 0x42, 0xdf, 0x01, 0x3c, 0xaf, 0x6a, 0xd7, 0x1d, 0x27, 0x07, 0x5d, 0xda,
	0x73, 0x90, 0x83, 0x2e, 0x75, 0xce, 0xe3, 0x35, 0x41, 0x77, 0x0b, 0x55, 0xf3, 0xd3, 0xa1, 0x6f,
	0x20, 0x36, 0x4b, 0xd0, 0x7a, 0x9e, 0x7e, 0x27, 0x0d, 0xc2, 0x72, 0x7d, 0x06, 0x05, 0x89, 0x74,
	0x4f, 0x20, 0xad, 0xa0, 0xdb, 0x59, 0x90, 0xbc, 0x51, 0x89, 0x28, 0xaf, 0x2f, 0x00, 0x9e, 0x53,
	0x94, 0x07, 0x71, 0xad, 0xe7, 0xe9, 0xf5, 0x8c, 0x64, 0x69, 0xb3, 0x1b, 0xaf, 0x0a, 0xb2, 0x1a,
	0xaa, 0xe4, 0x26, 0x43, 0x3f, 0xc1, 0xd8, 0x48, 0x40, 0xb9, 0x6e, 0x47, 0xf2, 0x54, 0x2b, 0x6f,
	0xce, 0xa4, 0x21, 0xb9, 0xd6, 0x05, 0xd7, 0x1a, 0x5a, 0xc9, 0xc2, 0xd5, 0x54, 0x45, 0xa2, 0xcc,
	0x7e, 0x00, 0x88, 0x62, 0xea, 0x83, 0xd4, 0x72, 0xdd, 0x90, 0x99, 0x09, 0xd3, 0x07, 0x32, 0xbe,
	0x2b, 0x08, 0x97, 0x51, 0xed, 0x1f, 0x08, 0x37, 0x1e, 0x7f, 0xea, 0x69, 0xe0, 0xa8, 0xa7, 0x81,
	0x5f, 0x3d, 0x0d, 0xbc, 0xed, 0x6b, 0x73, 0x47, 0x7d, 0x6d, 0xee, 0xb8, 0xaf, 0xcd, 0xed, 0x2e,
	0x5b, 0x36, 0x6f, 0x87, 0xa6, 0xde, 0x64, 0xfb, 0x29, 0xc2, 0x5d, 0x55, 0x9a, 0x1f, 0x7a, 0x34,
	0x30, 0x4f, 0x89, 0xbf, 0xc7, 0xb5, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x2b, 0xf8, 0x1e,
	0x17, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a validPubEvents by id.
	ValidPubEvents(ctx context.Context, in *QueryGetValidPubEventsRequest, opts ...grpc.CallOption) (*QueryGetValidPubEventsResponse, error)
	// Queries a list of validPubEvents items.
	ValidPubEventsAll(ctx context.Context, in *QueryAllValidPubEventsRequest, opts ...grpc.CallOption) (*QueryAllValidPubEventsResponse, error)
	// Queries a partPubEvents by id.
	PartPubEvents(ctx context.Context, in *QueryGetPartPubEventsRequest, opts ...grpc.CallOption) (*QueryGetPartPubEventsResponse, error)
	// Queries a list of partPubEvents items.
	PartPubEventsAll(ctx context.Context, in *QueryAllPartPubEventsRequest, opts ...grpc.CallOption) (*QueryAllPartPubEventsResponse, error)
	// Queries a createPubEvents by id.
	CreatePubEvents(ctx context.Context, in *QueryGetCreatePubEventsRequest, opts ...grpc.CallOption) (*QueryGetCreatePubEventsResponse, error)
	// Queries a list of createPubEvents items.
	CreatePubEventsAll(ctx context.Context, in *QueryAllCreatePubEventsRequest, opts ...grpc.CallOption) (*QueryAllCreatePubEventsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ValidPubEvents(ctx context.Context, in *QueryGetValidPubEventsRequest, opts ...grpc.CallOption) (*QueryGetValidPubEventsResponse, error) {
	out := new(QueryGetValidPubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Query/ValidPubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ValidPubEventsAll(ctx context.Context, in *QueryAllValidPubEventsRequest, opts ...grpc.CallOption) (*QueryAllValidPubEventsResponse, error) {
	out := new(QueryAllValidPubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Query/ValidPubEventsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PartPubEvents(ctx context.Context, in *QueryGetPartPubEventsRequest, opts ...grpc.CallOption) (*QueryGetPartPubEventsResponse, error) {
	out := new(QueryGetPartPubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Query/PartPubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PartPubEventsAll(ctx context.Context, in *QueryAllPartPubEventsRequest, opts ...grpc.CallOption) (*QueryAllPartPubEventsResponse, error) {
	out := new(QueryAllPartPubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Query/PartPubEventsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CreatePubEvents(ctx context.Context, in *QueryGetCreatePubEventsRequest, opts ...grpc.CallOption) (*QueryGetCreatePubEventsResponse, error) {
	out := new(QueryGetCreatePubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Query/CreatePubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CreatePubEventsAll(ctx context.Context, in *QueryAllCreatePubEventsRequest, opts ...grpc.CallOption) (*QueryAllCreatePubEventsResponse, error) {
	out := new(QueryAllCreatePubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Query/CreatePubEventsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a validPubEvents by id.
	ValidPubEvents(context.Context, *QueryGetValidPubEventsRequest) (*QueryGetValidPubEventsResponse, error)
	// Queries a list of validPubEvents items.
	ValidPubEventsAll(context.Context, *QueryAllValidPubEventsRequest) (*QueryAllValidPubEventsResponse, error)
	// Queries a partPubEvents by id.
	PartPubEvents(context.Context, *QueryGetPartPubEventsRequest) (*QueryGetPartPubEventsResponse, error)
	// Queries a list of partPubEvents items.
	PartPubEventsAll(context.Context, *QueryAllPartPubEventsRequest) (*QueryAllPartPubEventsResponse, error)
	// Queries a createPubEvents by id.
	CreatePubEvents(context.Context, *QueryGetCreatePubEventsRequest) (*QueryGetCreatePubEventsResponse, error)
	// Queries a list of createPubEvents items.
	CreatePubEventsAll(context.Context, *QueryAllCreatePubEventsRequest) (*QueryAllCreatePubEventsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ValidPubEvents(ctx context.Context, req *QueryGetValidPubEventsRequest) (*QueryGetValidPubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidPubEvents not implemented")
}
func (*UnimplementedQueryServer) ValidPubEventsAll(ctx context.Context, req *QueryAllValidPubEventsRequest) (*QueryAllValidPubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidPubEventsAll not implemented")
}
func (*UnimplementedQueryServer) PartPubEvents(ctx context.Context, req *QueryGetPartPubEventsRequest) (*QueryGetPartPubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartPubEvents not implemented")
}
func (*UnimplementedQueryServer) PartPubEventsAll(ctx context.Context, req *QueryAllPartPubEventsRequest) (*QueryAllPartPubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartPubEventsAll not implemented")
}
func (*UnimplementedQueryServer) CreatePubEvents(ctx context.Context, req *QueryGetCreatePubEventsRequest) (*QueryGetCreatePubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePubEvents not implemented")
}
func (*UnimplementedQueryServer) CreatePubEventsAll(ctx context.Context, req *QueryAllCreatePubEventsRequest) (*QueryAllCreatePubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePubEventsAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ValidPubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetValidPubEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidPubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Query/ValidPubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidPubEvents(ctx, req.(*QueryGetValidPubEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ValidPubEventsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllValidPubEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidPubEventsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Query/ValidPubEventsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidPubEventsAll(ctx, req.(*QueryAllValidPubEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PartPubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPartPubEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PartPubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Query/PartPubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PartPubEvents(ctx, req.(*QueryGetPartPubEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PartPubEventsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPartPubEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PartPubEventsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Query/PartPubEventsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PartPubEventsAll(ctx, req.(*QueryAllPartPubEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CreatePubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCreatePubEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CreatePubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Query/CreatePubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CreatePubEvents(ctx, req.(*QueryGetCreatePubEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CreatePubEventsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCreatePubEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CreatePubEventsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Query/CreatePubEventsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CreatePubEventsAll(ctx, req.(*QueryAllCreatePubEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VoroshilovMax.bettery.publicevents.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidPubEvents",
			Handler:    _Query_ValidPubEvents_Handler,
		},
		{
			MethodName: "ValidPubEventsAll",
			Handler:    _Query_ValidPubEventsAll_Handler,
		},
		{
			MethodName: "PartPubEvents",
			Handler:    _Query_PartPubEvents_Handler,
		},
		{
			MethodName: "PartPubEventsAll",
			Handler:    _Query_PartPubEventsAll_Handler,
		},
		{
			MethodName: "CreatePubEvents",
			Handler:    _Query_CreatePubEvents_Handler,
		},
		{
			MethodName: "CreatePubEventsAll",
			Handler:    _Query_CreatePubEventsAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publicevents/query.proto",
}

func (m *QueryGetValidPubEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetValidPubEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetValidPubEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetValidPubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetValidPubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetValidPubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidPubEvents != nil {
		{
			size, err := m.ValidPubEvents.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllValidPubEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllValidPubEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllValidPubEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllValidPubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllValidPubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllValidPubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidPubEvents) > 0 {
		for iNdEx := len(m.ValidPubEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidPubEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPartPubEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPartPubEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPartPubEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPartPubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPartPubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPartPubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PartPubEvents != nil {
		{
			size, err := m.PartPubEvents.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPartPubEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPartPubEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPartPubEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPartPubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPartPubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPartPubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PartPubEvents) > 0 {
		for iNdEx := len(m.PartPubEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PartPubEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCreatePubEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCreatePubEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCreatePubEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCreatePubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCreatePubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCreatePubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatePubEvents != nil {
		{
			size, err := m.CreatePubEvents.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCreatePubEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCreatePubEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCreatePubEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCreatePubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCreatePubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCreatePubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.CreatePubEvents) > 0 {
		for iNdEx := len(m.CreatePubEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CreatePubEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetValidPubEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetValidPubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ValidPubEvents != nil {
		l = m.ValidPubEvents.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllValidPubEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllValidPubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ValidPubEvents) > 0 {
		for _, e := range m.ValidPubEvents {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPartPubEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetPartPubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PartPubEvents != nil {
		l = m.PartPubEvents.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPartPubEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPartPubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PartPubEvents) > 0 {
		for _, e := range m.PartPubEvents {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCreatePubEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetCreatePubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CreatePubEvents != nil {
		l = m.CreatePubEvents.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCreatePubEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCreatePubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CreatePubEvents) > 0 {
		for _, e := range m.CreatePubEvents {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetValidPubEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetValidPubEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetValidPubEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetValidPubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetValidPubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetValidPubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidPubEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ValidPubEvents == nil {
				m.ValidPubEvents = &ValidPubEvents{}
			}
			if err := m.ValidPubEvents.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllValidPubEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllValidPubEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllValidPubEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllValidPubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllValidPubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllValidPubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidPubEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidPubEvents = append(m.ValidPubEvents, &ValidPubEvents{})
			if err := m.ValidPubEvents[len(m.ValidPubEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPartPubEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPartPubEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPartPubEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPartPubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPartPubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPartPubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartPubEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PartPubEvents == nil {
				m.PartPubEvents = &PartPubEvents{}
			}
			if err := m.PartPubEvents.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPartPubEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPartPubEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPartPubEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPartPubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPartPubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPartPubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartPubEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PartPubEvents = append(m.PartPubEvents, &PartPubEvents{})
			if err := m.PartPubEvents[len(m.PartPubEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCreatePubEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCreatePubEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCreatePubEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCreatePubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCreatePubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCreatePubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatePubEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatePubEvents == nil {
				m.CreatePubEvents = &CreatePubEvents{}
			}
			if err := m.CreatePubEvents.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCreatePubEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCreatePubEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCreatePubEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCreatePubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCreatePubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCreatePubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatePubEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatePubEvents = append(m.CreatePubEvents, &CreatePubEvents{})
			if err := m.CreatePubEvents[len(m.CreatePubEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
