// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: publicevents/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # proto/tx/message
type MsgCreateRefundPubEvents struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PubId   uint64 `protobuf:"varint,2,opt,name=pubId,proto3" json:"pubId,omitempty"`
	Purpose string `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
}

func (m *MsgCreateRefundPubEvents) Reset()         { *m = MsgCreateRefundPubEvents{} }
func (m *MsgCreateRefundPubEvents) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRefundPubEvents) ProtoMessage()    {}
func (*MsgCreateRefundPubEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{0}
}
func (m *MsgCreateRefundPubEvents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateRefundPubEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateRefundPubEvents.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateRefundPubEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRefundPubEvents.Merge(m, src)
}
func (m *MsgCreateRefundPubEvents) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateRefundPubEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRefundPubEvents.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRefundPubEvents proto.InternalMessageInfo

func (m *MsgCreateRefundPubEvents) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateRefundPubEvents) GetPubId() uint64 {
	if m != nil {
		return m.PubId
	}
	return 0
}

func (m *MsgCreateRefundPubEvents) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

type MsgCreateRefundPubEventsResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateRefundPubEventsResponse) Reset()         { *m = MsgCreateRefundPubEventsResponse{} }
func (m *MsgCreateRefundPubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRefundPubEventsResponse) ProtoMessage()    {}
func (*MsgCreateRefundPubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{1}
}
func (m *MsgCreateRefundPubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateRefundPubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateRefundPubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateRefundPubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRefundPubEventsResponse.Merge(m, src)
}
func (m *MsgCreateRefundPubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateRefundPubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRefundPubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRefundPubEventsResponse proto.InternalMessageInfo

func (m *MsgCreateRefundPubEventsResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgCreateRefPubEvents struct {
	Creator        string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PubId          uint64   `protobuf:"varint,2,opt,name=pubId,proto3" json:"pubId,omitempty"`
	RefOneAddr     []string `protobuf:"bytes,3,rep,name=refOneAddr,proto3" json:"refOneAddr,omitempty"`
	RefOneAmount   []string `protobuf:"bytes,4,rep,name=refOneAmount,proto3" json:"refOneAmount,omitempty"`
	RefTwoAddr     []string `protobuf:"bytes,5,rep,name=refTwoAddr,proto3" json:"refTwoAddr,omitempty"`
	RefTwoAmount   []string `protobuf:"bytes,6,rep,name=refTwoAmount,proto3" json:"refTwoAmount,omitempty"`
	RefThreeAddr   []string `protobuf:"bytes,7,rep,name=refThreeAddr,proto3" json:"refThreeAddr,omitempty"`
	RefThreeAmount []string `protobuf:"bytes,8,rep,name=refThreeAmount,proto3" json:"refThreeAmount,omitempty"`
	PayToComp      string   `protobuf:"bytes,9,opt,name=payToComp,proto3" json:"payToComp,omitempty"`
}

func (m *MsgCreateRefPubEvents) Reset()         { *m = MsgCreateRefPubEvents{} }
func (m *MsgCreateRefPubEvents) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRefPubEvents) ProtoMessage()    {}
func (*MsgCreateRefPubEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{2}
}
func (m *MsgCreateRefPubEvents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateRefPubEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateRefPubEvents.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateRefPubEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRefPubEvents.Merge(m, src)
}
func (m *MsgCreateRefPubEvents) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateRefPubEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRefPubEvents.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRefPubEvents proto.InternalMessageInfo

func (m *MsgCreateRefPubEvents) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateRefPubEvents) GetPubId() uint64 {
	if m != nil {
		return m.PubId
	}
	return 0
}

func (m *MsgCreateRefPubEvents) GetRefOneAddr() []string {
	if m != nil {
		return m.RefOneAddr
	}
	return nil
}

func (m *MsgCreateRefPubEvents) GetRefOneAmount() []string {
	if m != nil {
		return m.RefOneAmount
	}
	return nil
}

func (m *MsgCreateRefPubEvents) GetRefTwoAddr() []string {
	if m != nil {
		return m.RefTwoAddr
	}
	return nil
}

func (m *MsgCreateRefPubEvents) GetRefTwoAmount() []string {
	if m != nil {
		return m.RefTwoAmount
	}
	return nil
}

func (m *MsgCreateRefPubEvents) GetRefThreeAddr() []string {
	if m != nil {
		return m.RefThreeAddr
	}
	return nil
}

func (m *MsgCreateRefPubEvents) GetRefThreeAmount() []string {
	if m != nil {
		return m.RefThreeAmount
	}
	return nil
}

func (m *MsgCreateRefPubEvents) GetPayToComp() string {
	if m != nil {
		return m.PayToComp
	}
	return ""
}

type MsgCreateRefPubEventsResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateRefPubEventsResponse) Reset()         { *m = MsgCreateRefPubEventsResponse{} }
func (m *MsgCreateRefPubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRefPubEventsResponse) ProtoMessage()    {}
func (*MsgCreateRefPubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{3}
}
func (m *MsgCreateRefPubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateRefPubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateRefPubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateRefPubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRefPubEventsResponse.Merge(m, src)
}
func (m *MsgCreateRefPubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateRefPubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRefPubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRefPubEventsResponse proto.InternalMessageInfo

func (m *MsgCreateRefPubEventsResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgCreateFihishPubEvent struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PubId   uint64 `protobuf:"varint,2,opt,name=pubId,proto3" json:"pubId,omitempty"`
}

func (m *MsgCreateFihishPubEvent) Reset()         { *m = MsgCreateFihishPubEvent{} }
func (m *MsgCreateFihishPubEvent) String() string { return proto.CompactTextString(m) }
func (*MsgCreateFihishPubEvent) ProtoMessage()    {}
func (*MsgCreateFihishPubEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{4}
}
func (m *MsgCreateFihishPubEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateFihishPubEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateFihishPubEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateFihishPubEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateFihishPubEvent.Merge(m, src)
}
func (m *MsgCreateFihishPubEvent) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateFihishPubEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateFihishPubEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateFihishPubEvent proto.InternalMessageInfo

func (m *MsgCreateFihishPubEvent) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateFihishPubEvent) GetPubId() uint64 {
	if m != nil {
		return m.PubId
	}
	return 0
}

type MsgCreateFihishPubEventResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateFihishPubEventResponse) Reset()         { *m = MsgCreateFihishPubEventResponse{} }
func (m *MsgCreateFihishPubEventResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateFihishPubEventResponse) ProtoMessage()    {}
func (*MsgCreateFihishPubEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{5}
}
func (m *MsgCreateFihishPubEventResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateFihishPubEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateFihishPubEventResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateFihishPubEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateFihishPubEventResponse.Merge(m, src)
}
func (m *MsgCreateFihishPubEventResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateFihishPubEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateFihishPubEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateFihishPubEventResponse proto.InternalMessageInfo

func (m *MsgCreateFihishPubEventResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgCreateValidPubEvents struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PubId   uint64 `protobuf:"varint,2,opt,name=pubId,proto3" json:"pubId,omitempty"`
	Answers string `protobuf:"bytes,3,opt,name=answers,proto3" json:"answers,omitempty"`
	Reput   int64  `protobuf:"varint,4,opt,name=reput,proto3" json:"reput,omitempty"`
}

func (m *MsgCreateValidPubEvents) Reset()         { *m = MsgCreateValidPubEvents{} }
func (m *MsgCreateValidPubEvents) String() string { return proto.CompactTextString(m) }
func (*MsgCreateValidPubEvents) ProtoMessage()    {}
func (*MsgCreateValidPubEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{6}
}
func (m *MsgCreateValidPubEvents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateValidPubEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateValidPubEvents.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateValidPubEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateValidPubEvents.Merge(m, src)
}
func (m *MsgCreateValidPubEvents) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateValidPubEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateValidPubEvents.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateValidPubEvents proto.InternalMessageInfo

func (m *MsgCreateValidPubEvents) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateValidPubEvents) GetPubId() uint64 {
	if m != nil {
		return m.PubId
	}
	return 0
}

func (m *MsgCreateValidPubEvents) GetAnswers() string {
	if m != nil {
		return m.Answers
	}
	return ""
}

func (m *MsgCreateValidPubEvents) GetReput() int64 {
	if m != nil {
		return m.Reput
	}
	return 0
}

type MsgCreateValidPubEventsResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateValidPubEventsResponse) Reset()         { *m = MsgCreateValidPubEventsResponse{} }
func (m *MsgCreateValidPubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateValidPubEventsResponse) ProtoMessage()    {}
func (*MsgCreateValidPubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{7}
}
func (m *MsgCreateValidPubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateValidPubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateValidPubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateValidPubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateValidPubEventsResponse.Merge(m, src)
}
func (m *MsgCreateValidPubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateValidPubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateValidPubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateValidPubEventsResponse proto.InternalMessageInfo

func (m *MsgCreateValidPubEventsResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgCreatePartPubEvents struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PubId   uint64 `protobuf:"varint,2,opt,name=pubId,proto3" json:"pubId,omitempty"`
	Answers string `protobuf:"bytes,3,opt,name=answers,proto3" json:"answers,omitempty"`
	Amount  string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgCreatePartPubEvents) Reset()         { *m = MsgCreatePartPubEvents{} }
func (m *MsgCreatePartPubEvents) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePartPubEvents) ProtoMessage()    {}
func (*MsgCreatePartPubEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{8}
}
func (m *MsgCreatePartPubEvents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePartPubEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePartPubEvents.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePartPubEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePartPubEvents.Merge(m, src)
}
func (m *MsgCreatePartPubEvents) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePartPubEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePartPubEvents.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePartPubEvents proto.InternalMessageInfo

func (m *MsgCreatePartPubEvents) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreatePartPubEvents) GetPubId() uint64 {
	if m != nil {
		return m.PubId
	}
	return 0
}

func (m *MsgCreatePartPubEvents) GetAnswers() string {
	if m != nil {
		return m.Answers
	}
	return ""
}

func (m *MsgCreatePartPubEvents) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgCreatePartPubEventsResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreatePartPubEventsResponse) Reset()         { *m = MsgCreatePartPubEventsResponse{} }
func (m *MsgCreatePartPubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePartPubEventsResponse) ProtoMessage()    {}
func (*MsgCreatePartPubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{9}
}
func (m *MsgCreatePartPubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePartPubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePartPubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePartPubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePartPubEventsResponse.Merge(m, src)
}
func (m *MsgCreatePartPubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePartPubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePartPubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePartPubEventsResponse proto.InternalMessageInfo

func (m *MsgCreatePartPubEventsResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgCreateCreatePubEvents struct {
	Creator      string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PubId        uint64   `protobuf:"varint,2,opt,name=pubId,proto3" json:"pubId,omitempty"`
	Question     string   `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Answers      []string `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`
	PremAmount   string   `protobuf:"bytes,5,opt,name=premAmount,proto3" json:"premAmount,omitempty"`
	StartTime    int64    `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime      int64    `protobuf:"varint,7,opt,name=endTime,proto3" json:"endTime,omitempty"`
	ExpertAmount int64    `protobuf:"varint,8,opt,name=expertAmount,proto3" json:"expertAmount,omitempty"`
	Advisor      string   `protobuf:"bytes,9,opt,name=advisor,proto3" json:"advisor,omitempty"`
}

func (m *MsgCreateCreatePubEvents) Reset()         { *m = MsgCreateCreatePubEvents{} }
func (m *MsgCreateCreatePubEvents) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCreatePubEvents) ProtoMessage()    {}
func (*MsgCreateCreatePubEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{10}
}
func (m *MsgCreateCreatePubEvents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCreatePubEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCreatePubEvents.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCreatePubEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCreatePubEvents.Merge(m, src)
}
func (m *MsgCreateCreatePubEvents) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCreatePubEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCreatePubEvents.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCreatePubEvents proto.InternalMessageInfo

func (m *MsgCreateCreatePubEvents) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateCreatePubEvents) GetPubId() uint64 {
	if m != nil {
		return m.PubId
	}
	return 0
}

func (m *MsgCreateCreatePubEvents) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *MsgCreateCreatePubEvents) GetAnswers() []string {
	if m != nil {
		return m.Answers
	}
	return nil
}

func (m *MsgCreateCreatePubEvents) GetPremAmount() string {
	if m != nil {
		return m.PremAmount
	}
	return ""
}

func (m *MsgCreateCreatePubEvents) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *MsgCreateCreatePubEvents) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *MsgCreateCreatePubEvents) GetExpertAmount() int64 {
	if m != nil {
		return m.ExpertAmount
	}
	return 0
}

func (m *MsgCreateCreatePubEvents) GetAdvisor() string {
	if m != nil {
		return m.Advisor
	}
	return ""
}

type MsgCreateCreatePubEventsResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateCreatePubEventsResponse) Reset()         { *m = MsgCreateCreatePubEventsResponse{} }
func (m *MsgCreateCreatePubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCreatePubEventsResponse) ProtoMessage()    {}
func (*MsgCreateCreatePubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{11}
}
func (m *MsgCreateCreatePubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCreatePubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCreatePubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCreatePubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCreatePubEventsResponse.Merge(m, src)
}
func (m *MsgCreateCreatePubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCreatePubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCreatePubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCreatePubEventsResponse proto.InternalMessageInfo

func (m *MsgCreateCreatePubEventsResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgCreateRefundPubEvents)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateRefundPubEvents")
	proto.RegisterType((*MsgCreateRefundPubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateRefundPubEventsResponse")
	proto.RegisterType((*MsgCreateRefPubEvents)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateRefPubEvents")
	proto.RegisterType((*MsgCreateRefPubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateRefPubEventsResponse")
	proto.RegisterType((*MsgCreateFihishPubEvent)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateFihishPubEvent")
	proto.RegisterType((*MsgCreateFihishPubEventResponse)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateFihishPubEventResponse")
	proto.RegisterType((*MsgCreateValidPubEvents)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateValidPubEvents")
	proto.RegisterType((*MsgCreateValidPubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateValidPubEventsResponse")
	proto.RegisterType((*MsgCreatePartPubEvents)(nil), "VoroshilovMax.bettery.publicevents.MsgCreatePartPubEvents")
	proto.RegisterType((*MsgCreatePartPubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.MsgCreatePartPubEventsResponse")
	proto.RegisterType((*MsgCreateCreatePubEvents)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateCreatePubEvents")
	proto.RegisterType((*MsgCreateCreatePubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateCreatePubEventsResponse")
}

func init() { proto.RegisterFile("publicevents/tx.proto", fileDescriptor_ec5dc76a403d6247) }

var fileDescriptor_ec5dc76a403d6247 = []byte{
	// 701 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x93, 0x36, 0x69, 0x46, 0xa8, 0x07, 0xd3, 0x16, 0x2b, 0x02, 0x13, 0x0c, 0x42, 0x39,
	0x25, 0x50, 0xc4, 0x81, 0x9f, 0x4b, 0x5b, 0x40, 0xea, 0xa1, 0x6a, 0x65, 0x55, 0x3d, 0x70, 0xa9,
	0xec, 0x7a, 0xdb, 0x58, 0x6a, 0xbc, 0xcb, 0xee, 0x3a, 0x4d, 0x78, 0x0a, 0x84, 0x04, 0x42, 0xe2,
	0xca, 0x4b, 0xf0, 0x06, 0x1c, 0x7b, 0xe4, 0x88, 0xda, 0x17, 0x41, 0x5e, 0xaf, 0x37, 0xde, 0xd4,
	0x16, 0x72, 0x2a, 0x8e, 0x33, 0xfb, 0x7d, 0xdf, 0x7c, 0xbb, 0x99, 0x99, 0x18, 0xd6, 0x48, 0xec,
	0x9f, 0x85, 0xc7, 0x68, 0x84, 0x22, 0xce, 0xfa, 0x7c, 0xdc, 0x23, 0x14, 0x73, 0x6c, 0x3a, 0x87,
	0x98, 0x62, 0x36, 0x08, 0xcf, 0xf0, 0x68, 0xd7, 0x1b, 0xf7, 0x7c, 0xc4, 0x39, 0xa2, 0x93, 0x5e,
	0x1e, 0xdc, 0x7e, 0xa4, 0x51, 0x29, 0x3a, 0x89, 0xa3, 0xe0, 0x88, 0xc4, 0xfe, 0x51, 0x9a, 0x49,
	0x95, 0xda, 0x0f, 0x66, 0x51, 0xd7, 0x21, 0x0f, 0x35, 0xc8, 0x49, 0x38, 0x08, 0xd9, 0x60, 0x8a,
	0x2a, 0x04, 0x8d, 0xbc, 0xb3, 0xb0, 0xa0, 0x98, 0xa3, 0x81, 0x88, 0x47, 0xf9, 0x75, 0x8c, 0x6e,
	0xfb, 0x98, 0x22, 0x8f, 0xa3, 0x6b, 0x28, 0x27, 0x00, 0x6b, 0x97, 0x9d, 0x6e, 0x8b, 0x53, 0x57,
	0x5c, 0x6d, 0x3f, 0xf6, 0xdf, 0x0a, 0x84, 0x69, 0x41, 0x53, 0xd0, 0x30, 0xb5, 0x8c, 0x8e, 0xd1,
	0x6d, 0xb9, 0x59, 0x68, 0xae, 0xc2, 0x12, 0x89, 0xfd, 0x9d, 0xc0, 0xaa, 0x75, 0x8c, 0xee, 0xa2,
	0x9b, 0x06, 0x09, 0x9e, 0xc4, 0x94, 0x60, 0x86, 0xac, 0x7a, 0x8a, 0x97, 0xa1, 0xb3, 0x01, 0x9d,
	0xb2, 0x2a, 0x2e, 0x62, 0x04, 0x47, 0x0c, 0x99, 0x2b, 0x50, 0x0b, 0x03, 0x51, 0x68, 0xd1, 0xad,
	0x85, 0x81, 0xf3, 0xb3, 0x06, 0x6b, 0x79, 0xd2, 0xfc, 0xbe, 0x6c, 0x00, 0x8a, 0x4e, 0xf6, 0x22,
	0xb4, 0x19, 0x04, 0xd4, 0xaa, 0x77, 0xea, 0xdd, 0x96, 0x9b, 0xcb, 0x98, 0x0e, 0xdc, 0x92, 0xd1,
	0x10, 0xc7, 0x11, 0xb7, 0x16, 0x05, 0x42, 0xcb, 0x49, 0x8d, 0x83, 0x73, 0x2c, 0x34, 0x96, 0x94,
	0x86, 0xcc, 0x48, 0x8d, 0x24, 0x4a, 0x35, 0x1a, 0x4a, 0x43, 0xe5, 0x32, 0xcc, 0x80, 0xa2, 0xd4,
	0x49, 0x73, 0x8a, 0xc9, 0x72, 0xe6, 0x63, 0x58, 0x51, 0x71, 0xaa, 0xb4, 0x2c, 0x50, 0x33, 0x59,
	0xf3, 0x2e, 0xb4, 0x88, 0x37, 0x39, 0xc0, 0xdb, 0x78, 0x48, 0xac, 0x96, 0x78, 0x85, 0x69, 0xc2,
	0xe9, 0xc3, 0xbd, 0xc2, 0xa7, 0x2b, 0x7d, 0xec, 0x1d, 0xb8, 0xa3, 0x08, 0xef, 0x44, 0x63, 0x66,
	0x9c, 0xaa, 0xaf, 0xed, 0x3c, 0x85, 0xfb, 0x25, 0x52, 0xa5, 0xd5, 0x27, 0xb9, 0xea, 0x87, 0x49,
	0xc7, 0xdf, 0xa8, 0x07, 0xbd, 0x88, 0x9d, 0x23, 0xca, 0xb2, 0x1e, 0x94, 0x61, 0x82, 0xa7, 0x88,
	0xc4, 0xc9, 0xcf, 0x6b, 0x74, 0xeb, 0x6e, 0x1a, 0x68, 0x6e, 0xf5, 0xd2, 0xa5, 0x6e, 0x3f, 0xc2,
	0xba, 0xa2, 0xec, 0x7b, 0x94, 0xff, 0x0f, 0xb3, 0xeb, 0xd0, 0xf0, 0xb2, 0x66, 0x4c, 0x0e, 0x64,
	0xe4, 0x3c, 0x01, 0xbb, 0xb8, 0x76, 0xa9, 0xdb, 0xaf, 0xb5, 0xdc, 0x84, 0x4b, 0xe2, 0xdc, 0x86,
	0xdb, 0xb0, 0xfc, 0x21, 0x46, 0x8c, 0x87, 0x38, 0x92, 0x8e, 0x55, 0x9c, 0xbf, 0x4c, 0x3a, 0x40,
	0xea, 0x32, 0x36, 0x00, 0xa1, 0x68, 0x28, 0xfb, 0x79, 0x49, 0xf0, 0x72, 0x99, 0xa4, 0x97, 0x19,
	0xf7, 0x28, 0x3f, 0x08, 0x87, 0xc8, 0x6a, 0x88, 0x5f, 0x67, 0x9a, 0x48, 0x74, 0x51, 0x14, 0x88,
	0xb3, 0xa6, 0x38, 0xcb, 0xc2, 0x64, 0x9e, 0xd0, 0x98, 0x20, 0xca, 0xd5, 0xa4, 0x24, 0xc7, 0x5a,
	0x4e, 0xb8, 0x0a, 0x46, 0x21, 0xc3, 0x54, 0x4e, 0x49, 0x16, 0x6a, 0x3b, 0x69, 0xe6, 0x5d, 0xca,
	0x1e, 0x73, 0xe3, 0x47, 0x13, 0xea, 0xbb, 0xec, 0xd4, 0xfc, 0x6e, 0xc0, 0x5a, 0xf1, 0xce, 0x7c,
	0xdd, 0xfb, 0xf7, 0x3f, 0x4a, 0xaf, 0x6c, 0x17, 0xb6, 0xdf, 0xdc, 0x84, 0xad, 0x5c, 0x7f, 0x36,
	0xc0, 0x2c, 0x58, 0x9b, 0x2f, 0xaa, 0x8a, 0x4f, 0x7d, 0x6d, 0xce, 0x4d, 0x55, 0xa6, 0xbe, 0x19,
	0xb0, 0x5a, 0xb8, 0x5f, 0x5e, 0x55, 0xd2, 0xd6, 0xc9, 0xed, 0xed, 0x1b, 0x90, 0x0b, 0xac, 0xcd,
	0x2c, 0x9f, 0x6a, 0xd6, 0x74, 0x72, 0x45, 0x6b, 0x25, 0xbb, 0xe7, 0x8b, 0x01, 0xb7, 0x8b, 0x36,
	0xcd, 0xcb, 0x4a, 0xe2, 0x1a, 0xb7, 0xbd, 0x35, 0x3f, 0x57, 0xf9, 0x9a, 0x0e, 0xc0, 0xec, 0x4a,
	0xa9, 0x36, 0x00, 0x33, 0xec, 0x8a, 0x03, 0x50, 0x32, 0xb6, 0x5b, 0x7b, 0xbf, 0x2e, 0x6d, 0xe3,
	0xe2, 0xd2, 0x36, 0xfe, 0x5c, 0xda, 0xc6, 0xa7, 0x2b, 0x7b, 0xe1, 0xe2, 0xca, 0x5e, 0xf8, 0x7d,
	0x65, 0x2f, 0xbc, 0x7f, 0x7e, 0x1a, 0xf2, 0x41, 0xec, 0xf7, 0x8e, 0xf1, 0xb0, 0xaf, 0x55, 0xea,
	0xcb, 0x4a, 0xfd, 0x71, 0x5f, 0xff, 0x52, 0x9c, 0x10, 0xc4, 0xfc, 0x86, 0xf8, 0x58, 0x7a, 0xf6,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x2c, 0x50, 0x8c, 0x46, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreateRefundPubEvents(ctx context.Context, in *MsgCreateRefundPubEvents, opts ...grpc.CallOption) (*MsgCreateRefundPubEventsResponse, error)
	CreateRefPubEvents(ctx context.Context, in *MsgCreateRefPubEvents, opts ...grpc.CallOption) (*MsgCreateRefPubEventsResponse, error)
	CreateFihishPubEvent(ctx context.Context, in *MsgCreateFihishPubEvent, opts ...grpc.CallOption) (*MsgCreateFihishPubEventResponse, error)
	CreateValidPubEvents(ctx context.Context, in *MsgCreateValidPubEvents, opts ...grpc.CallOption) (*MsgCreateValidPubEventsResponse, error)
	CreatePartPubEvents(ctx context.Context, in *MsgCreatePartPubEvents, opts ...grpc.CallOption) (*MsgCreatePartPubEventsResponse, error)
	CreateCreatePubEvents(ctx context.Context, in *MsgCreateCreatePubEvents, opts ...grpc.CallOption) (*MsgCreateCreatePubEventsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateRefundPubEvents(ctx context.Context, in *MsgCreateRefundPubEvents, opts ...grpc.CallOption) (*MsgCreateRefundPubEventsResponse, error) {
	out := new(MsgCreateRefundPubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Msg/CreateRefundPubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateRefPubEvents(ctx context.Context, in *MsgCreateRefPubEvents, opts ...grpc.CallOption) (*MsgCreateRefPubEventsResponse, error) {
	out := new(MsgCreateRefPubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Msg/CreateRefPubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateFihishPubEvent(ctx context.Context, in *MsgCreateFihishPubEvent, opts ...grpc.CallOption) (*MsgCreateFihishPubEventResponse, error) {
	out := new(MsgCreateFihishPubEventResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Msg/CreateFihishPubEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateValidPubEvents(ctx context.Context, in *MsgCreateValidPubEvents, opts ...grpc.CallOption) (*MsgCreateValidPubEventsResponse, error) {
	out := new(MsgCreateValidPubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Msg/CreateValidPubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreatePartPubEvents(ctx context.Context, in *MsgCreatePartPubEvents, opts ...grpc.CallOption) (*MsgCreatePartPubEventsResponse, error) {
	out := new(MsgCreatePartPubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Msg/CreatePartPubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateCreatePubEvents(ctx context.Context, in *MsgCreateCreatePubEvents, opts ...grpc.CallOption) (*MsgCreateCreatePubEventsResponse, error) {
	out := new(MsgCreateCreatePubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Msg/CreateCreatePubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreateRefundPubEvents(context.Context, *MsgCreateRefundPubEvents) (*MsgCreateRefundPubEventsResponse, error)
	CreateRefPubEvents(context.Context, *MsgCreateRefPubEvents) (*MsgCreateRefPubEventsResponse, error)
	CreateFihishPubEvent(context.Context, *MsgCreateFihishPubEvent) (*MsgCreateFihishPubEventResponse, error)
	CreateValidPubEvents(context.Context, *MsgCreateValidPubEvents) (*MsgCreateValidPubEventsResponse, error)
	CreatePartPubEvents(context.Context, *MsgCreatePartPubEvents) (*MsgCreatePartPubEventsResponse, error)
	CreateCreatePubEvents(context.Context, *MsgCreateCreatePubEvents) (*MsgCreateCreatePubEventsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateRefundPubEvents(ctx context.Context, req *MsgCreateRefundPubEvents) (*MsgCreateRefundPubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRefundPubEvents not implemented")
}
func (*UnimplementedMsgServer) CreateRefPubEvents(ctx context.Context, req *MsgCreateRefPubEvents) (*MsgCreateRefPubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRefPubEvents not implemented")
}
func (*UnimplementedMsgServer) CreateFihishPubEvent(ctx context.Context, req *MsgCreateFihishPubEvent) (*MsgCreateFihishPubEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFihishPubEvent not implemented")
}
func (*UnimplementedMsgServer) CreateValidPubEvents(ctx context.Context, req *MsgCreateValidPubEvents) (*MsgCreateValidPubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateValidPubEvents not implemented")
}
func (*UnimplementedMsgServer) CreatePartPubEvents(ctx context.Context, req *MsgCreatePartPubEvents) (*MsgCreatePartPubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePartPubEvents not implemented")
}
func (*UnimplementedMsgServer) CreateCreatePubEvents(ctx context.Context, req *MsgCreateCreatePubEvents) (*MsgCreateCreatePubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCreatePubEvents not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateRefundPubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateRefundPubEvents)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateRefundPubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Msg/CreateRefundPubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateRefundPubEvents(ctx, req.(*MsgCreateRefundPubEvents))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateRefPubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateRefPubEvents)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateRefPubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Msg/CreateRefPubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateRefPubEvents(ctx, req.(*MsgCreateRefPubEvents))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateFihishPubEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateFihishPubEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateFihishPubEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Msg/CreateFihishPubEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateFihishPubEvent(ctx, req.(*MsgCreateFihishPubEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateValidPubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateValidPubEvents)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateValidPubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Msg/CreateValidPubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateValidPubEvents(ctx, req.(*MsgCreateValidPubEvents))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreatePartPubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePartPubEvents)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePartPubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Msg/CreatePartPubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePartPubEvents(ctx, req.(*MsgCreatePartPubEvents))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateCreatePubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCreatePubEvents)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCreatePubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Msg/CreateCreatePubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCreatePubEvents(ctx, req.(*MsgCreateCreatePubEvents))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VoroshilovMax.bettery.publicevents.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRefundPubEvents",
			Handler:    _Msg_CreateRefundPubEvents_Handler,
		},
		{
			MethodName: "CreateRefPubEvents",
			Handler:    _Msg_CreateRefPubEvents_Handler,
		},
		{
			MethodName: "CreateFihishPubEvent",
			Handler:    _Msg_CreateFihishPubEvent_Handler,
		},
		{
			MethodName: "CreateValidPubEvents",
			Handler:    _Msg_CreateValidPubEvents_Handler,
		},
		{
			MethodName: "CreatePartPubEvents",
			Handler:    _Msg_CreatePartPubEvents_Handler,
		},
		{
			MethodName: "CreateCreatePubEvents",
			Handler:    _Msg_CreateCreatePubEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publicevents/tx.proto",
}

func (m *MsgCreateRefundPubEvents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateRefundPubEvents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateRefundPubEvents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Purpose) > 0 {
		i -= len(m.Purpose)
		copy(dAtA[i:], m.Purpose)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Purpose)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PubId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PubId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateRefundPubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateRefundPubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateRefundPubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateRefPubEvents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateRefPubEvents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateRefPubEvents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PayToComp) > 0 {
		i -= len(m.PayToComp)
		copy(dAtA[i:], m.PayToComp)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PayToComp)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.RefThreeAmount) > 0 {
		for iNdEx := len(m.RefThreeAmount) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RefThreeAmount[iNdEx])
			copy(dAtA[i:], m.RefThreeAmount[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.RefThreeAmount[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.RefThreeAddr) > 0 {
		for iNdEx := len(m.RefThreeAddr) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RefThreeAddr[iNdEx])
			copy(dAtA[i:], m.RefThreeAddr[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.RefThreeAddr[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.RefTwoAmount) > 0 {
		for iNdEx := len(m.RefTwoAmount) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RefTwoAmount[iNdEx])
			copy(dAtA[i:], m.RefTwoAmount[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.RefTwoAmount[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.RefTwoAddr) > 0 {
		for iNdEx := len(m.RefTwoAddr) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RefTwoAddr[iNdEx])
			copy(dAtA[i:], m.RefTwoAddr[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.RefTwoAddr[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.RefOneAmount) > 0 {
		for iNdEx := len(m.RefOneAmount) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RefOneAmount[iNdEx])
			copy(dAtA[i:], m.RefOneAmount[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.RefOneAmount[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.RefOneAddr) > 0 {
		for iNdEx := len(m.RefOneAddr) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RefOneAddr[iNdEx])
			copy(dAtA[i:], m.RefOneAddr[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.RefOneAddr[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PubId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PubId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateRefPubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateRefPubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateRefPubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateFihishPubEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateFihishPubEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateFihishPubEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PubId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PubId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateFihishPubEventResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateFihishPubEventResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateFihishPubEventResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateValidPubEvents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateValidPubEvents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateValidPubEvents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reput != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Reput))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Answers) > 0 {
		i -= len(m.Answers)
		copy(dAtA[i:], m.Answers)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Answers)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PubId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PubId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateValidPubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateValidPubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateValidPubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePartPubEvents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePartPubEvents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePartPubEvents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Answers) > 0 {
		i -= len(m.Answers)
		copy(dAtA[i:], m.Answers)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Answers)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PubId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PubId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePartPubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePartPubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePartPubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCreatePubEvents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCreatePubEvents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCreatePubEvents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Advisor) > 0 {
		i -= len(m.Advisor)
		copy(dAtA[i:], m.Advisor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Advisor)))
		i--
		dAtA[i] = 0x4a
	}
	if m.ExpertAmount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExpertAmount))
		i--
		dAtA[i] = 0x40
	}
	if m.EndTime != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EndTime))
		i--
		dAtA[i] = 0x38
	}
	if m.StartTime != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StartTime))
		i--
		dAtA[i] = 0x30
	}
	if len(m.PremAmount) > 0 {
		i -= len(m.PremAmount)
		copy(dAtA[i:], m.PremAmount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PremAmount)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Answers) > 0 {
		for iNdEx := len(m.Answers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Answers[iNdEx])
			copy(dAtA[i:], m.Answers[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Answers[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Question) > 0 {
		i -= len(m.Question)
		copy(dAtA[i:], m.Question)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Question)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PubId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PubId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCreatePubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCreatePubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCreatePubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateRefundPubEvents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PubId != 0 {
		n += 1 + sovTx(uint64(m.PubId))
	}
	l = len(m.Purpose)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateRefundPubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgCreateRefPubEvents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PubId != 0 {
		n += 1 + sovTx(uint64(m.PubId))
	}
	if len(m.RefOneAddr) > 0 {
		for _, s := range m.RefOneAddr {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.RefOneAmount) > 0 {
		for _, s := range m.RefOneAmount {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.RefTwoAddr) > 0 {
		for _, s := range m.RefTwoAddr {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.RefTwoAmount) > 0 {
		for _, s := range m.RefTwoAmount {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.RefThreeAddr) > 0 {
		for _, s := range m.RefThreeAddr {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.RefThreeAmount) > 0 {
		for _, s := range m.RefThreeAmount {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.PayToComp)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateRefPubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgCreateFihishPubEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PubId != 0 {
		n += 1 + sovTx(uint64(m.PubId))
	}
	return n
}

func (m *MsgCreateFihishPubEventResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgCreateValidPubEvents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PubId != 0 {
		n += 1 + sovTx(uint64(m.PubId))
	}
	l = len(m.Answers)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Reput != 0 {
		n += 1 + sovTx(uint64(m.Reput))
	}
	return n
}

func (m *MsgCreateValidPubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgCreatePartPubEvents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PubId != 0 {
		n += 1 + sovTx(uint64(m.PubId))
	}
	l = len(m.Answers)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreatePartPubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgCreateCreatePubEvents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PubId != 0 {
		n += 1 + sovTx(uint64(m.PubId))
	}
	l = len(m.Question)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Answers) > 0 {
		for _, s := range m.Answers {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.PremAmount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.StartTime != 0 {
		n += 1 + sovTx(uint64(m.StartTime))
	}
	if m.EndTime != 0 {
		n += 1 + sovTx(uint64(m.EndTime))
	}
	if m.ExpertAmount != 0 {
		n += 1 + sovTx(uint64(m.ExpertAmount))
	}
	l = len(m.Advisor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateCreatePubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateRefundPubEvents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateRefundPubEvents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateRefundPubEvents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			m.PubId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PubId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Purpose", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Purpose = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateRefundPubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateRefundPubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateRefundPubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateRefPubEvents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateRefPubEvents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateRefPubEvents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			m.PubId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PubId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefOneAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefOneAddr = append(m.RefOneAddr, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefOneAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefOneAmount = append(m.RefOneAmount, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefTwoAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefTwoAddr = append(m.RefTwoAddr, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefTwoAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefTwoAmount = append(m.RefTwoAmount, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefThreeAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefThreeAddr = append(m.RefThreeAddr, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefThreeAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefThreeAmount = append(m.RefThreeAmount, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayToComp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayToComp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateRefPubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateRefPubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateRefPubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateFihishPubEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateFihishPubEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateFihishPubEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			m.PubId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PubId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateFihishPubEventResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateFihishPubEventResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateFihishPubEventResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateValidPubEvents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateValidPubEvents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateValidPubEvents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			m.PubId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PubId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Answers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Answers = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reput", wireType)
			}
			m.Reput = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reput |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateValidPubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateValidPubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateValidPubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePartPubEvents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePartPubEvents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePartPubEvents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			m.PubId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PubId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Answers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Answers = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePartPubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePartPubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePartPubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCreatePubEvents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCreatePubEvents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCreatePubEvents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			m.PubId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PubId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Question", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Question = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Answers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Answers = append(m.Answers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PremAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PremAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			m.EndTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpertAmount", wireType)
			}
			m.ExpertAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpertAmount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Advisor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Advisor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCreatePubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCreatePubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCreatePubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
