// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: publicevents/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # proto/tx/message
type MsgCreateFihishPubEvent struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PubId   string `protobuf:"bytes,2,opt,name=pubId,proto3" json:"pubId,omitempty"`
}

func (m *MsgCreateFihishPubEvent) Reset()         { *m = MsgCreateFihishPubEvent{} }
func (m *MsgCreateFihishPubEvent) String() string { return proto.CompactTextString(m) }
func (*MsgCreateFihishPubEvent) ProtoMessage()    {}
func (*MsgCreateFihishPubEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{0}
}
func (m *MsgCreateFihishPubEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateFihishPubEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateFihishPubEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateFihishPubEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateFihishPubEvent.Merge(m, src)
}
func (m *MsgCreateFihishPubEvent) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateFihishPubEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateFihishPubEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateFihishPubEvent proto.InternalMessageInfo

func (m *MsgCreateFihishPubEvent) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateFihishPubEvent) GetPubId() string {
	if m != nil {
		return m.PubId
	}
	return ""
}

type MsgCreateFihishPubEventResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateFihishPubEventResponse) Reset()         { *m = MsgCreateFihishPubEventResponse{} }
func (m *MsgCreateFihishPubEventResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateFihishPubEventResponse) ProtoMessage()    {}
func (*MsgCreateFihishPubEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{1}
}
func (m *MsgCreateFihishPubEventResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateFihishPubEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateFihishPubEventResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateFihishPubEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateFihishPubEventResponse.Merge(m, src)
}
func (m *MsgCreateFihishPubEventResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateFihishPubEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateFihishPubEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateFihishPubEventResponse proto.InternalMessageInfo

func (m *MsgCreateFihishPubEventResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateFihishPubEvent struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PubId   string `protobuf:"bytes,3,opt,name=pubId,proto3" json:"pubId,omitempty"`
}

func (m *MsgUpdateFihishPubEvent) Reset()         { *m = MsgUpdateFihishPubEvent{} }
func (m *MsgUpdateFihishPubEvent) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateFihishPubEvent) ProtoMessage()    {}
func (*MsgUpdateFihishPubEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{2}
}
func (m *MsgUpdateFihishPubEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateFihishPubEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateFihishPubEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateFihishPubEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateFihishPubEvent.Merge(m, src)
}
func (m *MsgUpdateFihishPubEvent) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateFihishPubEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateFihishPubEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateFihishPubEvent proto.InternalMessageInfo

func (m *MsgUpdateFihishPubEvent) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateFihishPubEvent) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateFihishPubEvent) GetPubId() string {
	if m != nil {
		return m.PubId
	}
	return ""
}

type MsgUpdateFihishPubEventResponse struct {
}

func (m *MsgUpdateFihishPubEventResponse) Reset()         { *m = MsgUpdateFihishPubEventResponse{} }
func (m *MsgUpdateFihishPubEventResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateFihishPubEventResponse) ProtoMessage()    {}
func (*MsgUpdateFihishPubEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{3}
}
func (m *MsgUpdateFihishPubEventResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateFihishPubEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateFihishPubEventResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateFihishPubEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateFihishPubEventResponse.Merge(m, src)
}
func (m *MsgUpdateFihishPubEventResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateFihishPubEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateFihishPubEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateFihishPubEventResponse proto.InternalMessageInfo

type MsgDeleteFihishPubEvent struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDeleteFihishPubEvent) Reset()         { *m = MsgDeleteFihishPubEvent{} }
func (m *MsgDeleteFihishPubEvent) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteFihishPubEvent) ProtoMessage()    {}
func (*MsgDeleteFihishPubEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{4}
}
func (m *MsgDeleteFihishPubEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteFihishPubEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteFihishPubEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteFihishPubEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteFihishPubEvent.Merge(m, src)
}
func (m *MsgDeleteFihishPubEvent) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteFihishPubEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteFihishPubEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteFihishPubEvent proto.InternalMessageInfo

func (m *MsgDeleteFihishPubEvent) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteFihishPubEvent) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgDeleteFihishPubEventResponse struct {
}

func (m *MsgDeleteFihishPubEventResponse) Reset()         { *m = MsgDeleteFihishPubEventResponse{} }
func (m *MsgDeleteFihishPubEventResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteFihishPubEventResponse) ProtoMessage()    {}
func (*MsgDeleteFihishPubEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{5}
}
func (m *MsgDeleteFihishPubEventResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteFihishPubEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteFihishPubEventResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteFihishPubEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteFihishPubEventResponse.Merge(m, src)
}
func (m *MsgDeleteFihishPubEventResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteFihishPubEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteFihishPubEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteFihishPubEventResponse proto.InternalMessageInfo

type MsgCreateValidPubEvents struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PubId   uint64 `protobuf:"varint,2,opt,name=pubId,proto3" json:"pubId,omitempty"`
	Answers string `protobuf:"bytes,3,opt,name=answers,proto3" json:"answers,omitempty"`
	Reput   int64  `protobuf:"varint,4,opt,name=reput,proto3" json:"reput,omitempty"`
}

func (m *MsgCreateValidPubEvents) Reset()         { *m = MsgCreateValidPubEvents{} }
func (m *MsgCreateValidPubEvents) String() string { return proto.CompactTextString(m) }
func (*MsgCreateValidPubEvents) ProtoMessage()    {}
func (*MsgCreateValidPubEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{6}
}
func (m *MsgCreateValidPubEvents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateValidPubEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateValidPubEvents.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateValidPubEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateValidPubEvents.Merge(m, src)
}
func (m *MsgCreateValidPubEvents) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateValidPubEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateValidPubEvents.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateValidPubEvents proto.InternalMessageInfo

func (m *MsgCreateValidPubEvents) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateValidPubEvents) GetPubId() uint64 {
	if m != nil {
		return m.PubId
	}
	return 0
}

func (m *MsgCreateValidPubEvents) GetAnswers() string {
	if m != nil {
		return m.Answers
	}
	return ""
}

func (m *MsgCreateValidPubEvents) GetReput() int64 {
	if m != nil {
		return m.Reput
	}
	return 0
}

type MsgCreateValidPubEventsResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateValidPubEventsResponse) Reset()         { *m = MsgCreateValidPubEventsResponse{} }
func (m *MsgCreateValidPubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateValidPubEventsResponse) ProtoMessage()    {}
func (*MsgCreateValidPubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{7}
}
func (m *MsgCreateValidPubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateValidPubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateValidPubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateValidPubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateValidPubEventsResponse.Merge(m, src)
}
func (m *MsgCreateValidPubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateValidPubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateValidPubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateValidPubEventsResponse proto.InternalMessageInfo

func (m *MsgCreateValidPubEventsResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgCreatePartPubEvents struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PubId   uint64 `protobuf:"varint,2,opt,name=pubId,proto3" json:"pubId,omitempty"`
	Answers string `protobuf:"bytes,3,opt,name=answers,proto3" json:"answers,omitempty"`
	Amount  string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgCreatePartPubEvents) Reset()         { *m = MsgCreatePartPubEvents{} }
func (m *MsgCreatePartPubEvents) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePartPubEvents) ProtoMessage()    {}
func (*MsgCreatePartPubEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{8}
}
func (m *MsgCreatePartPubEvents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePartPubEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePartPubEvents.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePartPubEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePartPubEvents.Merge(m, src)
}
func (m *MsgCreatePartPubEvents) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePartPubEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePartPubEvents.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePartPubEvents proto.InternalMessageInfo

func (m *MsgCreatePartPubEvents) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreatePartPubEvents) GetPubId() uint64 {
	if m != nil {
		return m.PubId
	}
	return 0
}

func (m *MsgCreatePartPubEvents) GetAnswers() string {
	if m != nil {
		return m.Answers
	}
	return ""
}

func (m *MsgCreatePartPubEvents) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgCreatePartPubEventsResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreatePartPubEventsResponse) Reset()         { *m = MsgCreatePartPubEventsResponse{} }
func (m *MsgCreatePartPubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePartPubEventsResponse) ProtoMessage()    {}
func (*MsgCreatePartPubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{9}
}
func (m *MsgCreatePartPubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePartPubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePartPubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePartPubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePartPubEventsResponse.Merge(m, src)
}
func (m *MsgCreatePartPubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePartPubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePartPubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePartPubEventsResponse proto.InternalMessageInfo

func (m *MsgCreatePartPubEventsResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgCreateCreatePubEvents struct {
	Creator      string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PubId        uint64   `protobuf:"varint,2,opt,name=pubId,proto3" json:"pubId,omitempty"`
	Question     string   `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Answers      []string `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`
	PremAmount   string   `protobuf:"bytes,5,opt,name=premAmount,proto3" json:"premAmount,omitempty"`
	StartTime    int64    `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime      int64    `protobuf:"varint,7,opt,name=endTime,proto3" json:"endTime,omitempty"`
	ExpertAmount int64    `protobuf:"varint,8,opt,name=expertAmount,proto3" json:"expertAmount,omitempty"`
	Advisor      string   `protobuf:"bytes,9,opt,name=advisor,proto3" json:"advisor,omitempty"`
}

func (m *MsgCreateCreatePubEvents) Reset()         { *m = MsgCreateCreatePubEvents{} }
func (m *MsgCreateCreatePubEvents) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCreatePubEvents) ProtoMessage()    {}
func (*MsgCreateCreatePubEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{10}
}
func (m *MsgCreateCreatePubEvents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCreatePubEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCreatePubEvents.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCreatePubEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCreatePubEvents.Merge(m, src)
}
func (m *MsgCreateCreatePubEvents) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCreatePubEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCreatePubEvents.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCreatePubEvents proto.InternalMessageInfo

func (m *MsgCreateCreatePubEvents) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateCreatePubEvents) GetPubId() uint64 {
	if m != nil {
		return m.PubId
	}
	return 0
}

func (m *MsgCreateCreatePubEvents) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *MsgCreateCreatePubEvents) GetAnswers() []string {
	if m != nil {
		return m.Answers
	}
	return nil
}

func (m *MsgCreateCreatePubEvents) GetPremAmount() string {
	if m != nil {
		return m.PremAmount
	}
	return ""
}

func (m *MsgCreateCreatePubEvents) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *MsgCreateCreatePubEvents) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *MsgCreateCreatePubEvents) GetExpertAmount() int64 {
	if m != nil {
		return m.ExpertAmount
	}
	return 0
}

func (m *MsgCreateCreatePubEvents) GetAdvisor() string {
	if m != nil {
		return m.Advisor
	}
	return ""
}

type MsgCreateCreatePubEventsResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateCreatePubEventsResponse) Reset()         { *m = MsgCreateCreatePubEventsResponse{} }
func (m *MsgCreateCreatePubEventsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCreatePubEventsResponse) ProtoMessage()    {}
func (*MsgCreateCreatePubEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5dc76a403d6247, []int{11}
}
func (m *MsgCreateCreatePubEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCreatePubEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCreatePubEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCreatePubEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCreatePubEventsResponse.Merge(m, src)
}
func (m *MsgCreateCreatePubEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCreatePubEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCreatePubEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCreatePubEventsResponse proto.InternalMessageInfo

func (m *MsgCreateCreatePubEventsResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgCreateFihishPubEvent)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateFihishPubEvent")
	proto.RegisterType((*MsgCreateFihishPubEventResponse)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateFihishPubEventResponse")
	proto.RegisterType((*MsgUpdateFihishPubEvent)(nil), "VoroshilovMax.bettery.publicevents.MsgUpdateFihishPubEvent")
	proto.RegisterType((*MsgUpdateFihishPubEventResponse)(nil), "VoroshilovMax.bettery.publicevents.MsgUpdateFihishPubEventResponse")
	proto.RegisterType((*MsgDeleteFihishPubEvent)(nil), "VoroshilovMax.bettery.publicevents.MsgDeleteFihishPubEvent")
	proto.RegisterType((*MsgDeleteFihishPubEventResponse)(nil), "VoroshilovMax.bettery.publicevents.MsgDeleteFihishPubEventResponse")
	proto.RegisterType((*MsgCreateValidPubEvents)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateValidPubEvents")
	proto.RegisterType((*MsgCreateValidPubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateValidPubEventsResponse")
	proto.RegisterType((*MsgCreatePartPubEvents)(nil), "VoroshilovMax.bettery.publicevents.MsgCreatePartPubEvents")
	proto.RegisterType((*MsgCreatePartPubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.MsgCreatePartPubEventsResponse")
	proto.RegisterType((*MsgCreateCreatePubEvents)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateCreatePubEvents")
	proto.RegisterType((*MsgCreateCreatePubEventsResponse)(nil), "VoroshilovMax.bettery.publicevents.MsgCreateCreatePubEventsResponse")
}

func init() { proto.RegisterFile("publicevents/tx.proto", fileDescriptor_ec5dc76a403d6247) }

var fileDescriptor_ec5dc76a403d6247 = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x93, 0x34, 0x69, 0x46, 0x88, 0x83, 0x69, 0x8b, 0x15, 0x21, 0x13, 0x0c, 0x87, 0x9e,
	0x1c, 0x28, 0xe2, 0x02, 0x5c, 0x68, 0x0a, 0x52, 0x0f, 0x11, 0x55, 0x04, 0x95, 0xe0, 0x52, 0xd9,
	0xf1, 0x92, 0xac, 0x94, 0x78, 0x97, 0xdd, 0x75, 0x48, 0xf8, 0x15, 0x5c, 0x40, 0x48, 0xfc, 0x00,
	0xfe, 0x0a, 0xc7, 0x1e, 0x39, 0xa2, 0xe4, 0x8f, 0x20, 0xaf, 0x3f, 0x62, 0xa7, 0xeb, 0x92, 0xa4,
	0xe2, 0x38, 0xbb, 0xef, 0xbd, 0x79, 0x3b, 0x23, 0x3d, 0x2d, 0xec, 0xd1, 0xc0, 0x1d, 0xe2, 0x1e,
	0x1a, 0x23, 0x5f, 0xf0, 0x96, 0x98, 0xd8, 0x94, 0x11, 0x41, 0x74, 0xeb, 0x8c, 0x30, 0xc2, 0x07,
	0x78, 0x48, 0xc6, 0x1d, 0x67, 0x62, 0xbb, 0x48, 0x08, 0xc4, 0xa6, 0x76, 0x16, 0xdc, 0xb8, 0x9f,
	0xa3, 0x7e, 0xc0, 0x03, 0xcc, 0x07, 0xe7, 0x34, 0x70, 0xcf, 0xe5, 0x49, 0x24, 0xb4, 0x04, 0x1a,
	0x3b, 0x43, 0xec, 0x2d, 0x30, 0x3c, 0x06, 0x59, 0x39, 0x10, 0x75, 0x98, 0xb8, 0x8c, 0x79, 0x90,
	0xc3, 0xf4, 0x18, 0x72, 0x04, 0xba, 0x84, 0xb2, 0x4e, 0xe0, 0x76, 0x87, 0xf7, 0xdb, 0xf2, 0xf6,
	0x95, 0x74, 0x74, 0x1a, 0xb8, 0x2f, 0x43, 0x84, 0x6e, 0x40, 0x4d, 0xb2, 0x08, 0x33, 0xb4, 0xa6,
	0x76, 0x50, 0xef, 0x26, 0xa5, 0xbe, 0x0b, 0xdb, 0x34, 0x70, 0x4f, 0x3c, 0xa3, 0x24, 0xcf, 0xa3,
	0xc2, 0x7a, 0x04, 0x77, 0x0b, 0xa4, 0xba, 0x88, 0x53, 0xe2, 0x73, 0xa4, 0xdf, 0x84, 0x12, 0xf6,
	0xa4, 0x5a, 0xa5, 0x5b, 0xc2, 0x9e, 0xf5, 0x4e, 0x76, 0x7f, 0x4b, 0xbd, 0x75, 0xba, 0x47, 0x22,
	0xa5, 0x44, 0x64, 0xe1, 0xa6, 0x9c, 0x75, 0x73, 0x4f, 0xba, 0x51, 0x49, 0x27, 0x6e, 0xac, 0xb6,
	0xec, 0x7e, 0x8c, 0x86, 0x68, 0xf3, 0xee, 0x71, 0x1f, 0x95, 0x48, 0xda, 0x67, 0x9a, 0x99, 0xf1,
	0x59, 0xb8, 0xd0, 0x04, 0xc1, 0x57, 0x9d, 0x71, 0x25, 0x7e, 0x55, 0x88, 0x77, 0x7c, 0xfe, 0x09,
	0x31, 0x1e, 0xbf, 0x36, 0x29, 0x43, 0x3c, 0x43, 0x34, 0x10, 0x46, 0xa5, 0xa9, 0x1d, 0x94, 0xbb,
	0x51, 0x91, 0xdb, 0x49, 0xbe, 0x75, 0xe1, 0x4e, 0x3e, 0xc3, 0x7e, 0x4a, 0x39, 0x75, 0x98, 0xf8,
	0x1f, 0x66, 0xf7, 0xa1, 0xea, 0x8c, 0x48, 0xe0, 0x47, 0x6e, 0xeb, 0xdd, 0xb8, 0xb2, 0x1e, 0x82,
	0xa9, 0xee, 0x5d, 0xe8, 0xf6, 0x5b, 0x09, 0x8c, 0x94, 0x12, 0x13, 0x37, 0x36, 0xdc, 0x80, 0x9d,
	0x8f, 0x01, 0xe2, 0x02, 0x13, 0x3f, 0x76, 0x9c, 0xd6, 0xd9, 0xc7, 0x54, 0x9a, 0xe5, 0xec, 0x63,
	0x4c, 0x00, 0xca, 0xd0, 0xe8, 0x45, 0xf4, 0xa0, 0x6d, 0xc9, 0xcb, 0x9c, 0xe8, 0x77, 0xa0, 0xce,
	0x85, 0xc3, 0xc4, 0x1b, 0x3c, 0x42, 0x46, 0x55, 0x6e, 0x67, 0x71, 0x10, 0xea, 0x22, 0xdf, 0x93,
	0x77, 0x35, 0x79, 0x97, 0x94, 0xba, 0x05, 0x37, 0xd0, 0x84, 0x22, 0x26, 0x62, 0xe5, 0x1d, 0x79,
	0x9d, 0x3b, 0x93, 0xae, 0xbc, 0x31, 0xe6, 0x84, 0x19, 0xf5, 0x78, 0xc4, 0x51, 0x69, 0x1d, 0x42,
	0xb3, 0x68, 0x2e, 0x45, 0xc3, 0x3c, 0xfc, 0x59, 0x83, 0x72, 0x87, 0xf7, 0xf5, 0xef, 0x1a, 0xec,
	0x2a, 0x23, 0xe1, 0x99, 0xfd, 0xef, 0x98, 0xb3, 0x0b, 0x42, 0xa0, 0xd1, 0xbe, 0x06, 0x39, 0xb5,
	0x1c, 0x5a, 0x53, 0xe6, 0xc5, 0xaa, 0xd6, 0x54, 0xe4, 0x95, 0xad, 0x5d, 0x15, 0x27, 0xd2, 0x9a,
	0x32, 0x4c, 0x56, 0xb5, 0xa6, 0x22, 0xaf, 0x6c, 0xed, 0xaa, 0x04, 0xca, 0x2c, 0x74, 0x29, 0x7f,
	0xd6, 0x5b, 0x68, 0x9e, 0xbc, 0xe6, 0x42, 0x0b, 0xe2, 0xe7, 0xab, 0x06, 0xb7, 0x54, 0x61, 0xf3,
	0x74, 0x2d, 0xf1, 0x1c, 0xb7, 0x71, 0xb4, 0x39, 0x37, 0xf5, 0xf5, 0x43, 0x83, 0x3d, 0x75, 0xaa,
	0x3c, 0x5f, 0x4b, 0x7d, 0x89, 0xdd, 0x38, 0xbe, 0x0e, 0x3b, 0x71, 0x77, 0xf4, 0xfa, 0xd7, 0xcc,
	0xd4, 0x2e, 0x66, 0xa6, 0xf6, 0x67, 0x66, 0x6a, 0x5f, 0xe6, 0xe6, 0xd6, 0xc5, 0xdc, 0xdc, 0xfa,
	0x3d, 0x37, 0xb7, 0xde, 0x3f, 0xe9, 0x63, 0x31, 0x08, 0x5c, 0xbb, 0x47, 0x46, 0xad, 0x5c, 0xa7,
	0x56, 0xdc, 0xa9, 0x35, 0x69, 0xe5, 0xbf, 0x30, 0x53, 0x8a, 0xb8, 0x5b, 0x95, 0xdf, 0x81, 0xc7,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x71, 0xfc, 0xcd, 0xdf, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreateFihishPubEvent(ctx context.Context, in *MsgCreateFihishPubEvent, opts ...grpc.CallOption) (*MsgCreateFihishPubEventResponse, error)
	UpdateFihishPubEvent(ctx context.Context, in *MsgUpdateFihishPubEvent, opts ...grpc.CallOption) (*MsgUpdateFihishPubEventResponse, error)
	DeleteFihishPubEvent(ctx context.Context, in *MsgDeleteFihishPubEvent, opts ...grpc.CallOption) (*MsgDeleteFihishPubEventResponse, error)
	CreateValidPubEvents(ctx context.Context, in *MsgCreateValidPubEvents, opts ...grpc.CallOption) (*MsgCreateValidPubEventsResponse, error)
	CreatePartPubEvents(ctx context.Context, in *MsgCreatePartPubEvents, opts ...grpc.CallOption) (*MsgCreatePartPubEventsResponse, error)
	CreateCreatePubEvents(ctx context.Context, in *MsgCreateCreatePubEvents, opts ...grpc.CallOption) (*MsgCreateCreatePubEventsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateFihishPubEvent(ctx context.Context, in *MsgCreateFihishPubEvent, opts ...grpc.CallOption) (*MsgCreateFihishPubEventResponse, error) {
	out := new(MsgCreateFihishPubEventResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Msg/CreateFihishPubEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateFihishPubEvent(ctx context.Context, in *MsgUpdateFihishPubEvent, opts ...grpc.CallOption) (*MsgUpdateFihishPubEventResponse, error) {
	out := new(MsgUpdateFihishPubEventResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Msg/UpdateFihishPubEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteFihishPubEvent(ctx context.Context, in *MsgDeleteFihishPubEvent, opts ...grpc.CallOption) (*MsgDeleteFihishPubEventResponse, error) {
	out := new(MsgDeleteFihishPubEventResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Msg/DeleteFihishPubEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateValidPubEvents(ctx context.Context, in *MsgCreateValidPubEvents, opts ...grpc.CallOption) (*MsgCreateValidPubEventsResponse, error) {
	out := new(MsgCreateValidPubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Msg/CreateValidPubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreatePartPubEvents(ctx context.Context, in *MsgCreatePartPubEvents, opts ...grpc.CallOption) (*MsgCreatePartPubEventsResponse, error) {
	out := new(MsgCreatePartPubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Msg/CreatePartPubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateCreatePubEvents(ctx context.Context, in *MsgCreateCreatePubEvents, opts ...grpc.CallOption) (*MsgCreateCreatePubEventsResponse, error) {
	out := new(MsgCreateCreatePubEventsResponse)
	err := c.cc.Invoke(ctx, "/VoroshilovMax.bettery.publicevents.Msg/CreateCreatePubEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreateFihishPubEvent(context.Context, *MsgCreateFihishPubEvent) (*MsgCreateFihishPubEventResponse, error)
	UpdateFihishPubEvent(context.Context, *MsgUpdateFihishPubEvent) (*MsgUpdateFihishPubEventResponse, error)
	DeleteFihishPubEvent(context.Context, *MsgDeleteFihishPubEvent) (*MsgDeleteFihishPubEventResponse, error)
	CreateValidPubEvents(context.Context, *MsgCreateValidPubEvents) (*MsgCreateValidPubEventsResponse, error)
	CreatePartPubEvents(context.Context, *MsgCreatePartPubEvents) (*MsgCreatePartPubEventsResponse, error)
	CreateCreatePubEvents(context.Context, *MsgCreateCreatePubEvents) (*MsgCreateCreatePubEventsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateFihishPubEvent(ctx context.Context, req *MsgCreateFihishPubEvent) (*MsgCreateFihishPubEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFihishPubEvent not implemented")
}
func (*UnimplementedMsgServer) UpdateFihishPubEvent(ctx context.Context, req *MsgUpdateFihishPubEvent) (*MsgUpdateFihishPubEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFihishPubEvent not implemented")
}
func (*UnimplementedMsgServer) DeleteFihishPubEvent(ctx context.Context, req *MsgDeleteFihishPubEvent) (*MsgDeleteFihishPubEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFihishPubEvent not implemented")
}
func (*UnimplementedMsgServer) CreateValidPubEvents(ctx context.Context, req *MsgCreateValidPubEvents) (*MsgCreateValidPubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateValidPubEvents not implemented")
}
func (*UnimplementedMsgServer) CreatePartPubEvents(ctx context.Context, req *MsgCreatePartPubEvents) (*MsgCreatePartPubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePartPubEvents not implemented")
}
func (*UnimplementedMsgServer) CreateCreatePubEvents(ctx context.Context, req *MsgCreateCreatePubEvents) (*MsgCreateCreatePubEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCreatePubEvents not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateFihishPubEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateFihishPubEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateFihishPubEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Msg/CreateFihishPubEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateFihishPubEvent(ctx, req.(*MsgCreateFihishPubEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateFihishPubEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateFihishPubEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateFihishPubEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Msg/UpdateFihishPubEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateFihishPubEvent(ctx, req.(*MsgUpdateFihishPubEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteFihishPubEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteFihishPubEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteFihishPubEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Msg/DeleteFihishPubEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteFihishPubEvent(ctx, req.(*MsgDeleteFihishPubEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateValidPubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateValidPubEvents)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateValidPubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Msg/CreateValidPubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateValidPubEvents(ctx, req.(*MsgCreateValidPubEvents))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreatePartPubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePartPubEvents)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePartPubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Msg/CreatePartPubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePartPubEvents(ctx, req.(*MsgCreatePartPubEvents))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateCreatePubEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCreatePubEvents)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCreatePubEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VoroshilovMax.bettery.publicevents.Msg/CreateCreatePubEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCreatePubEvents(ctx, req.(*MsgCreateCreatePubEvents))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VoroshilovMax.bettery.publicevents.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFihishPubEvent",
			Handler:    _Msg_CreateFihishPubEvent_Handler,
		},
		{
			MethodName: "UpdateFihishPubEvent",
			Handler:    _Msg_UpdateFihishPubEvent_Handler,
		},
		{
			MethodName: "DeleteFihishPubEvent",
			Handler:    _Msg_DeleteFihishPubEvent_Handler,
		},
		{
			MethodName: "CreateValidPubEvents",
			Handler:    _Msg_CreateValidPubEvents_Handler,
		},
		{
			MethodName: "CreatePartPubEvents",
			Handler:    _Msg_CreatePartPubEvents_Handler,
		},
		{
			MethodName: "CreateCreatePubEvents",
			Handler:    _Msg_CreateCreatePubEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publicevents/tx.proto",
}

func (m *MsgCreateFihishPubEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateFihishPubEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateFihishPubEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PubId) > 0 {
		i -= len(m.PubId)
		copy(dAtA[i:], m.PubId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PubId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateFihishPubEventResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateFihishPubEventResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateFihishPubEventResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateFihishPubEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateFihishPubEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateFihishPubEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PubId) > 0 {
		i -= len(m.PubId)
		copy(dAtA[i:], m.PubId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PubId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateFihishPubEventResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateFihishPubEventResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateFihishPubEventResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteFihishPubEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteFihishPubEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteFihishPubEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteFihishPubEventResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteFihishPubEventResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteFihishPubEventResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateValidPubEvents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateValidPubEvents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateValidPubEvents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reput != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Reput))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Answers) > 0 {
		i -= len(m.Answers)
		copy(dAtA[i:], m.Answers)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Answers)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PubId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PubId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateValidPubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateValidPubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateValidPubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePartPubEvents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePartPubEvents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePartPubEvents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Answers) > 0 {
		i -= len(m.Answers)
		copy(dAtA[i:], m.Answers)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Answers)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PubId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PubId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePartPubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePartPubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePartPubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCreatePubEvents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCreatePubEvents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCreatePubEvents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Advisor) > 0 {
		i -= len(m.Advisor)
		copy(dAtA[i:], m.Advisor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Advisor)))
		i--
		dAtA[i] = 0x4a
	}
	if m.ExpertAmount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExpertAmount))
		i--
		dAtA[i] = 0x40
	}
	if m.EndTime != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EndTime))
		i--
		dAtA[i] = 0x38
	}
	if m.StartTime != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StartTime))
		i--
		dAtA[i] = 0x30
	}
	if len(m.PremAmount) > 0 {
		i -= len(m.PremAmount)
		copy(dAtA[i:], m.PremAmount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PremAmount)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Answers) > 0 {
		for iNdEx := len(m.Answers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Answers[iNdEx])
			copy(dAtA[i:], m.Answers[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Answers[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Question) > 0 {
		i -= len(m.Question)
		copy(dAtA[i:], m.Question)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Question)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PubId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PubId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCreatePubEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCreatePubEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCreatePubEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateFihishPubEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PubId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateFihishPubEventResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateFihishPubEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.PubId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateFihishPubEventResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteFihishPubEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgDeleteFihishPubEventResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateValidPubEvents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PubId != 0 {
		n += 1 + sovTx(uint64(m.PubId))
	}
	l = len(m.Answers)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Reput != 0 {
		n += 1 + sovTx(uint64(m.Reput))
	}
	return n
}

func (m *MsgCreateValidPubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgCreatePartPubEvents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PubId != 0 {
		n += 1 + sovTx(uint64(m.PubId))
	}
	l = len(m.Answers)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreatePartPubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgCreateCreatePubEvents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PubId != 0 {
		n += 1 + sovTx(uint64(m.PubId))
	}
	l = len(m.Question)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Answers) > 0 {
		for _, s := range m.Answers {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.PremAmount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.StartTime != 0 {
		n += 1 + sovTx(uint64(m.StartTime))
	}
	if m.EndTime != 0 {
		n += 1 + sovTx(uint64(m.EndTime))
	}
	if m.ExpertAmount != 0 {
		n += 1 + sovTx(uint64(m.ExpertAmount))
	}
	l = len(m.Advisor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateCreatePubEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateFihishPubEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateFihishPubEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateFihishPubEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateFihishPubEventResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateFihishPubEventResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateFihishPubEventResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateFihishPubEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateFihishPubEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateFihishPubEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateFihishPubEventResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateFihishPubEventResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateFihishPubEventResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteFihishPubEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteFihishPubEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteFihishPubEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteFihishPubEventResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteFihishPubEventResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteFihishPubEventResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateValidPubEvents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateValidPubEvents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateValidPubEvents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			m.PubId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PubId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Answers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Answers = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reput", wireType)
			}
			m.Reput = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reput |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateValidPubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateValidPubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateValidPubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePartPubEvents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePartPubEvents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePartPubEvents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			m.PubId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PubId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Answers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Answers = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePartPubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePartPubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePartPubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCreatePubEvents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCreatePubEvents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCreatePubEvents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubId", wireType)
			}
			m.PubId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PubId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Question", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Question = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Answers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Answers = append(m.Answers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PremAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PremAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			m.EndTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpertAmount", wireType)
			}
			m.ExpertAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpertAmount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Advisor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Advisor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCreatePubEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCreatePubEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCreatePubEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
